export const data = {
    "S1S1_1": "Hola amig@!",
    "S1S1_2": "Hola.",
    "S1S1_3": "Soy el mensajero del rey. Tenemos una misi\u00f3n para usted. El rey ha escuchado que usted es el mejor artesano del reino y que encuentra excelentes soluciones para cualquier tipo de problema. \u00bfEs esto cierto?",
    "S1S1_4": "Bien, lo hago lo mejor que puedo.",
    "S1S1_5": "\u00a1Curioso! Si es verdad, entonces coja sus cosas y acompa\u00f1eme a la ciudad del Reino de Lalandia, Empat\u00eda!",
    "S1S2_1": "Ah! Me alegra que aceptase mi invitaci\u00f3n. Yo soy el rey de Lalandia. Necesito un nuevo carruaje para viajar por todo el reino. Y me han dicho que eres el mejor dise\u00f1ador en todo el reino. Entonces mi misi\u00f3n, si la acepta, es construir para m\u00ed el mejor carruaje del mundo!",
    "S1S2_2": "Yo soy la reina de Lalandia. Tambi\u00e9n usar\u00e9 este nuevo carruaje para recorrer el reino. Necesito que sea un carruaje pr\u00e1ctico como tambi\u00e9n el m\u00e1s hermoso del mundo.",
    "S1S2_3": "S\u00ed, s\u00ed! Necesita ser todo eso! Y lo necesitamos dentro de 6 meses. Iremos al Gran Consejo de Reyes, donde todos los Reyes del Norte se encontrar\u00e1n. Ahora, \u00bfaceptas?",
    "S1S2_4": "Mi reina, mi rey, ser\u00eda un honor aceptar esta desafiante misi\u00f3n. Por lo tanto, lo acepto. Pero antes de dise\u00f1ar este carro, tengo muchas preguntas que hacerles para poder entender lo que necesitan.",
    "S1S2_5": "Ahora ya conoces todos los detalles. Acabamos de dec\u00edrtelos. \u00a1Ahora ve! La reina y yo recibimos al Pr\u00edncipe del Mar del Sur, as\u00ed que no tenemos tiempo para discutirlo m\u00e1s. \u00a1Buena suerte!",
    "S1S2_6": "\u00bfPero qu\u00e9 tipo de carruaje debo dise\u00f1ar? \u00bfCu\u00e1les ser\u00e1n las diferentes funciones del carruaje? No tengo ni idea de lo que el rey y la reina realmente necesitan... esto es muy confuso!",
    "S1S3_1": "\u00bfQu\u00e9 significa exactamente el carruaje m\u00e1s pr\u00e1ctico y bonito del mundo? Entrar\u00e1s en un mundo lleno de personajes que te dir\u00e1n diferentes opiniones sobre c\u00f3mo creen que deber\u00eda ser este carruaje.",
    "S1S3_2": "\u00bfOcurre algo?",
    "S1S3_3": "Bueno... El rey y la reina me dieron la misi\u00f3n de construir un nuevo carruaje para ellos. Pero necesito m\u00e1s informaci\u00f3n para poder dise\u00f1arlo correctamente. \u00bfPara qu\u00e9 lo necesitan? \u00bfQu\u00e9 debe hacer? \u00bfEn qu\u00e9 tipo de carretera suelen viajar? \u00bfQu\u00e9 tan grande deber\u00eda ser? \u00bfCu\u00e1les deber\u00edan ser sus funciones? Fueron muy difusos con su petici\u00f3n.",
    "S1S3_4": "\u00a1Aha, tienes que construir un carruaje fuerte y verdaderamente resistente! Deber\u00eda ser seguro para la familia real viajar en \u00e9l. Y no hay necesidad de lujo, hay belleza en la dureza. Pero tal vez deber\u00edas ir por ah\u00ed y reunir m\u00e1s puntos de vista.",
    "S1S4_1": "Los largos viajes pueden ser agotadores. El carruaje debe ser c\u00f3modo. \u00a1Y no digo eso solo para m\u00ed, sino tambi\u00e9n para la pareja real!",
    "S1S4_2": "El carruaje deber\u00eda ser el m\u00e1s rico que se haya hecho en el reino para mostrar el poder del rey y la riqueza de su tierra, debe ser una obra de arte y un lujo.",
    "S1S4_3": "La familia real tiene muchas cosas para llevar, ropa, regalos, etc. As\u00ed que necesito espacio para poner todo eso en el carruaje.",
    "S1S4_4": "Piensa en los caballos que arrastrar\u00e1n el carruaje. Si quieres ir r\u00e1pido, tiene que ser peque\u00f1o y ligero. De lo contrario, se cansar\u00e1n r\u00e1pidamente.",
    "S1S4_5": "Ser\u00eda fant\u00e1stico si el carruaje pudiera adaptarse a algunos de mis instrumentos m\u00e9dicos y poder organizar mis medicamentos. Podr\u00eda tener todo a mi disposici\u00f3n en caso de necesidad.",
    "S1S4_6": "La pareja real tiene que comer, pero puede elegir quedarse en otros palacios o en las casas de los invitados. No hay necesidad de una mini cocina a bordo.",
    "S1S4_7": "El carruaje debe ser liviano y eficiente. No est\u00e1s construyendo una torre que tenga que aguantar durante siglos, sino un carrito ambulante. Haz que sea liviano y \u00e1gil.",
    "S1S4_8": "El tiempo es dinero. Un rey y una reina no tienen tiempo que perder deambulando por ah\u00ed. Solo hazlo r\u00e1pido.",
    "S1S4_9": "Haz que el carruaje sea c\u00f3modo porque las piedras del adoqu\u00edn aqu\u00ed son muy duras ... y los traseros del rey y la reina se resentir\u00e1n ... te lo puedo asegurar",
    "S1S4_10": "El carruaje debe reflejar la importancia del papel del rey en todo el mundo y la historia del reino y, por lo tanto, estar cargado de s\u00edmbolos hist\u00f3ricos, el carruaje deber\u00eda convertirse en un artefacto legendario.",
    "S1S4_11": "\u00a1Fuera de mi camino, hay algunas personas trabajando aqu\u00ed!",
    "S1S4_12": "No permitas que la familia real arruine el reino con este carruaje. Ya tienen mucho m\u00e1s de lo que nosotros, la gente, tenemos. Hazlo simple.",
    "S1S4_13": "El que viaja felizmente debe viajar ligero (Antoine de St Exupery)",
    "S1S4_14": "No tengo tiempo para discutir. Tengo carne que recoger.",
    "S1S5_1": "Ahora que ha reunido suficientes opiniones, puede regresar a su taller para comenzar a trabajar en su proyecto o continuar reuni\u00e9ndose con otras personas.",
    "S2S0": "\u00a1\u00c9ste es su taller! Bas\u00e1ndose en lo que ha escuchado, es hora de tomar algunas decisiones sobre qu\u00e9 tipo de transporte piensa que se ajusta mejor a las necesidades del Rey y la Reina.",
    "S2L1": "Lento",
    "S2L2": "R\u00e1pido",
    "S2L3": "Tosco",
    "S2L4": "Bello",
    "S2L5": "B\u00e1sico",
    "S2L6": "Lujoso",
    "S2L7": "Peque\u00f1o",
    "S2L8": "Grande",
    "S2L9": "Ligero",
    "S2L10": "\u00bfEl rey y la reina prefieren la velocidad alta o viajar m\u00e1s lento pero con seguridad a trav\u00e9s de todo tipo de caminos?",
    "S2L11": "\u00bfEl rey y la reina preferir\u00e1n un carruaje duradero o un carruaje lujoso?",
    "S2L12": "\u00bfEl rey y la reina preferir\u00e1n un carruaje minimalista pero pr\u00e1ctico o uno muy lujoso?",
    "S2L13": "\u00bfEl rey y la reina preferir\u00e1n un carruaje peque\u00f1o y r\u00e1pido o un carruaje c\u00f3modo m\u00e1s lento?",
    "S2L14": "\u00bfEl rey y la reina preferir\u00e1n un carro ligero b\u00e1sico o uno muy robusto?",
    "S2L15": "Fuerte",
    "S2S1": "Parece que no ha tomado decisiones acertadas... Un carruaje mediano no se ajustar\u00e1 a las necesidades del Rey y la Reina. Tome decisiones reales.",
    "S2S2": "\u00a1Qu\u00e9 carro tan prometedor! \u00a1Bien hecho!",
    "S3S1_1": "Antes de seguir adelante con nuestro plan, tal vez deber\u00edamos considerar ver los carruajes de otros reyes y reinas. \u00a1Esto podr\u00eda inspirarnos!",
    "S3S1_2": "El carruaje de la reina Patricia es el m\u00e1s r\u00e1pido dentro del Reino pero a menudo falla y se rompe.",
    "S3S1_3": "El carruaje de la reina Mihaela es el m\u00e1s hermoso pero no muy conveniente... un poco pesado y una pesadilla para limpiar (el barro se atasca en todos los elementos decorativos de las paredes exteriores).",
    "S3S1_4": "El carruaje del rey Pablo es el m\u00e1s fuerte dentro del Reino. Sobrevivi\u00f3 a muy malos caminos e incluso a muchos ataques y tuvo \u00e9xito siempre en mantener a salvo al rey y la reina.",
    "S3S1_5": "El carruaje de la Reina Ana es el m\u00e1s c\u00f3modo. Incluso el asiento para el cochero est\u00e1 hecho de materiales muy suaves y c\u00f3modos. Hace que cada viaje sea muy placentero.",
    "S3S1_6": "El carruaje del rey Tharrenos es el m\u00e1s grande. Ofrece un gran espacio. Viajando con este carruaje uno se siente como viajar sin salir de su sala de estar.",
    "S3S3_1": "Espero que este peque\u00f1o recorrido por los carruajes de otros reyes y reinas le haya inspirado. \u00a1Ahora sigamos con los nuestros!",
    "S4S1_1": "Con toda la informaci\u00f3n que recogi\u00f3 de las personas que ha conocido, los carruajes existentes que ha visto y su propio punto de vista e intuici\u00f3n, ahora es el momento de empezar a prototipar el carro. ",
    "S4S2_1": "Su carruaje es demasiado barato. \u00a1 Est\u00e1 construyendo el carruaje de la familia real! No es un carrito de comerciante!  ",
    "S4S2_2": " Su carruaje es tan simple que s\u00f3lo le llevar\u00e1 un par de semanas construirlo. Podemos invertir m\u00e1s tiempo ya que tenemos 6 meses para entregarlo. Vamos a mejorar nuestro carro  ",
    "S4S2_3": "Su carruaje es demasiado pesado y lento. Los viajes se har\u00e1n eternos.",
    "S4S2_4": "Su carruaje es demasiado r\u00fastico para un carruaje real, parece un carruaje de campesino.",
    "S4S2_5": "Tienes que hacer un carruaje no un carro. \u00a1H\u00e1galo m\u00e1s sofisticado!  ",
    "S4S2_6": "Su carruaje es demasiado fr\u00e1gil. Se romper\u00e1 en la primera piedra de adoqu\u00edn que le golpee. ",
    "S4S2_7": "\u00a1Est\u00e1s arruinando el Reino!  Reconsidere su dise\u00f1o eligiendo elementos menos costosos.  ",
    "S4S2_8": "La familia Real necesita el carruaje listo en 6 meses. Elija algunos elementos m\u00e1s simples para reducir el tiempo de construcci\u00f3n.  ",
    "S4S3_1": "Necesita mejorar su dise\u00f1o antes de continuar.",
    "S4S3_2": "\u00a1De acuerdo! \u00a1Procedamos con las pruebas!",
    "S5S0_1": "Ahora que su prototipo est\u00e1 listo, vamos a mostrarlo a algunas personas para ver lo que piensan de \u00e9l antes de presentarlo a los reyes.",
    "S5S1_1": "Bien, me parece bastante fuerte. Debemos probarlo antes de mostrarselo al rey y la reina.  ",
    "S5S1_2": "Bien hecho. Mi amigo. Es un carruaje muy bonito. \u00bfpero crees que puede atravesar calles estrechas? Deber\u00edas intentarlo antes de entregarlo.  ",
    "S5S1_3": "No est\u00e1 mal, no est\u00e1 mal... \u00bfpero crees que es lo suficientemente lujoso si la pareja real tiene que ir a una ceremonia? Preg\u00fanteselo a la gente antes de entregarlo al rey y la reina.  ",
    "S5S1_4": "Lo siento, no hay tiempo para charlar. ",
    "S5S1_5": "Tengo trabajo que hacer. Preg\u00fantele a otra persona.  ",
    "S5S1_6": "\u00bfMmm?",
    "S5S1_7": "Bas\u00e1ndose en los comentarios que acaba de recibir, \u00bfdesea revisar su dise\u00f1o o ignorar sus comentarios y mantener su dise\u00f1o como es? ",
    "S5S2_1": "Ahora est\u00e1 listo para la prueba en el mundo real. \u00bfest\u00e1 listo para ver si su carruaje es lo suficientemente bueno ahora? Lleve el carruaje afuera y par\u00e9se en el cruce de la carretera. Hay 3 caminos que puede elegir. Escoge uno de los 3 caminos.",
    "S5S2_2A": "Acabas de llegar a la ciudad con el carruaje y nadie se ha dado cuenta de tu llegada ... No es una buena se\u00f1al. \u00a1El Carro Real debe ser notado por todo el mundo! \u00a1Las multitudes deber\u00edan estar reuni\u00e9ndose a su alrededor! Deber\u00edas considerar hacerlo m\u00e1s llamativo ...",
    "S5S2_2": "Ha elegido que su carruaje sea seguido por artistas (m\u00fasicos, artistas), banderas y animales bellos como elefantes, jirafas, camellos, avestruces... para ir al Congreso de Reyes y Reinas! Lo que es bueno es que esto no impacta el dise\u00f1o de su carro sino que le permite presumir de carro temporalmente sin modificarlo \u00a1Bien hecho!",
    "S5S2_3A": "Acabas de llegar a la ciudad de tu viejo amigo el Se\u00f1or Christophe. \u00a1Qu\u00e9 casualidad! Est\u00e1n planeando viajar a Portalona al d\u00eda siguiente, al igual que tu carruaje. Deber\u00edas considerar compartirlo con ellos ...",
    "S5S2_3": "Ha elegido ahora dise\u00f1ar el carro para que pueda ser compartido. \u00a1Felicitaciones! La mayor\u00eda de los carros est\u00e1n estacionados durante el 80% de su tiempo, por lo que compartir significa ahorrar. Recuerde tambi\u00e9n pensar en c\u00f3mo dividir el tiempo de uso del carro.",
    "S5S2_4A": "Acabas de pasar el puente de Oslina ... \u00a1Emboscada! Una banda de ladrones! \u00a1Pero hurra! \u00a1Has logrado escapar! Deber\u00edas considerar proteger el carro ...",
    "S5S2_4": "\u00a1Ahora ha elegido rodear su carruaje con soldados y armas para sobrellevar la guerra! Lo bueno es que no tiene que cambiar nada sobre el dise\u00f1o de su carro. Esto le permite responder temporalmente a esta necesidad excepcional con poco esfuerzo. \u00a1Bien hecho!",
    "S5S2B": "Acaban de aparecer nuevas opciones en el taller, vuelve para descubrirlas.",
    "S5S2C": "Ahora que has aumentado tu carruaje, ll\u00e9valo fuera para probarlo.",
    "S6S1_1": "\u00a1Es el gran d\u00eda que hemos estado esperando! Es hora de que presentar nuestro carruaje al Rey y a la Reina.",
    "S6S1_2": "\u00a1Bien hecho! Ha hecho un trabajo fant\u00e1stico. Estoy muy contenta con el resultado.",
    "S6S1_3": "\u00a1S\u00ed, este carruaje es perfecto!",
    "S6S2_1": "Muchas gracias... \u00bfpero podr\u00eda hacerlo rosa?",
    "S6S2_2": "Gracias... \u00bfpero lo podr\u00eda hacer del color del arco iris?",
    "S6S2_3": "Es f\u00e1ntastico, pero me gustar\u00eda a\u00fan m\u00e1s con alas.",
    "S6S2_4": "Me gusta mucho, \u00bfpero lo podr\u00eda cubrir de plumas?",
    "S6S3_1": "\u00a1Ha hecho un trabajo incre\u00edble! \u00a1 Esto es una obra maestra! \u00a1Puede celebrarlo! Todo el Reino est\u00e1 agradecido. \u00a1 no s\u00e9 cu\u00e1les son tus planes para el futuro, pero no pierda esa creatividad suya!",
    "B1": "Mente creativa",
    "B2": "Pensamiento cr\u00edtico",
    "B3": "Oyente",
    "B4": "Nunca te rindes",
    "B5": "Solucionador\/a de problemas",
    "M1": "Ahora puedes seguir con el pr\u00f3ximo paso",
    "M2": "Selecciona un\/a personaje para recibir m\u00e1s mensajes",
    "M3": "Selecciona un\/a personaje",
    "next.page": "Pr\u00f3xima p\u00e1gina",
    "previous.page": "P\u00e0gina anterior",
    "see.result": "Comprueva los resultados",
    "next.step": "Siguiente paso",
    "start": "Comienza",
    "B6": "Cierra",
    "B7": "Pista",
    "B8": "Ir al taller",
    "B9": "Escribe tu nombre...",
    "B10": "Comienza el juego",
    "B11": "Carga el juego",
    "S4L1": "Ruedas",
    "S4L2": "Chasis",
    "S4L3": "Asiento del conductor",
    "S4L4": "Asientos interiores",
    "S4L5": "Carrocer\u00eda",
    "S4L6": "Equipaje",
    "N1L1": "Construye el mejor carruaje pr\u00e1ctico y atractivo para la familia real",
    "N1L2": "Personajes",
    "N1L3": "Indicadores",
    "N1L4": "Carruajes",
    "N1L5": "Ejemplos",
    "N1L6": "Tu carruaje",
    "N1L7": "Disrupciones",
    "N1L8": "Medallas",
    "N1L9": "La misi\u00f3n",
    "S6A1": "\u00a1Gracias mi reina! \u00a1Realmente disfrut\u00e9 trabajando en esto! Y he tenido muchas otras ideas al tratar de dise\u00f1ar el mejor carro, \u00bfquiz\u00e1s algunas les ser\u00edan \u00fatiles?",
    "S6A2": "Adelante!",
    "S6A3": "Bien, tal vez podr\u00edamos hacer el carro m\u00e1s...",
    "S6A4": "hermoso, rodeando el carruaje con animadores (m\u00fasicos, artistas), banderas y animales, \u00a1para ir al congreso de reyes y reinas! Apuesto a que todos quedar\u00e1n muy impresionados.",
    "S6A5": "Respetuoso con el medio ambiente, dise\u00f1ando el carro para que se pueda compartir. La mayor\u00eda de los carruajes est\u00e1n estacionados el 80% de su tiempo. \u00a1Comp\u00e1rtanlo!",
    "S6A6": "\u00bfTiene alguna sugerencia para m\u00ed?",
    "S6A7": "S\u00ed mi rey, quiz\u00e1s podr\u00eda proteger su carruaje prepar\u00e1ndolo para la guerra. No es suficiente con una carrocer\u00eda fuerte, debe rodear su carruaje con soldados y escudos. Seguramente impresionar\u00e1 a sus posibles atacantes."
}
