export const data = {
    "S1S1_1": "Hola amig@!",
    "S1S1_2": "Hola.",
    "S1S1_3": "Soy el mensajero del rey. Tenemos una misión para usted. El rey ha escuchado que usted es el mejor artesano del reino y que encuentra excelentes soluciones para cualquier tipo de problema. ¿Es esto cierto?",
    "S1S1_4": "Bien, lo hago lo mejor que puedo.",
    "S1S1_5": "¡Curioso! Si es verdad, entonces coja sus cosas y acompañeme a la ciudad del Reino de Lalandia, Empatía!",
    "S1S2_1": "Ah! Me alegra que aceptase mi invitación. Yo soy el rey de Lalandia. Necesito un nuevo carruaje para viajar por todo el reino. Y me han dicho que eres el mejor diseñador en todo el reino. Entonces mi misión, si la acepta, es construir para mí el mejor carruaje del mundo!",
    "S1S2_2": "Yo soy la reina de Lalandia. También usaré este nuevo carruaje para recorrer el reino. Necesito que sea un carruaje práctico como también el más hermoso del mundo.",
    "S1S2_3": "Sí, sí! Necesita ser todo eso! Y lo necesitamos dentro de 6 meses. Iremos al Gran Consejo de Reyes, donde todos los Reyes del Norte se encontrarán. Ahora, ¿aceptas?",
    "S1S2_4": "Mi reina, mi rey, sería un honor aceptar esta desafiante misión. Por lo tanto, lo acepto. Pero antes de diseñar este carro, tengo muchas preguntas que hacerles para poder entender lo que necesitan.",
    "S1S2_5": "Ahora ya conoces todos los detalles. Acabamos de decírtelos. ¡Ahora ve! La reina y yo recibimos al Príncipe del Mar del Sur, así que no tenemos tiempo para discutirlo más. ¡Buena suerte!",
    "S1S2_6": "¿Pero qué tipo de carruaje debo diseñar? ¿Cuáles serán las diferentes funciones del carruaje? No tengo ni idea de lo que el rey y la reina realmente necesitan... esto es muy confuso!",
    "S1S3_1": "¿Qué significa exactamente el carruaje más práctico y bonito del mundo? Entrarás en un mundo lleno de personajes que te dirán diferentes opiniones sobre cómo creen que debería ser este carruaje.",
    "S1S3_2": "¿Ocurre algo?",
    "S1S3_3": "Bueno... El rey y la reina me dieron la misión de construir un nuevo carruaje para ellos. Pero necesito más información para poder diseñarlo correctamente. ¿Para qué lo necesitan? ¿Qué debe hacer? ¿En qué tipo de carretera suelen viajar? ¿Qué tan grande debería ser? ¿Cuáles deberían ser sus funciones? Fueron muy difusos con su petición.",
    "S1S3_4": "¡Aha, tienes que construir un carruaje fuerte y verdaderamente resistente! Debería ser seguro para la familia real viajar en él. Y no hay necesidad de lujo, hay belleza en la dureza. Pero tal vez deberías ir por ahí y reunir más puntos de vista.",
    "S1S4_1": "Los largos viajes pueden ser agotadores. El carruaje debe ser cómodo. ¡Y no digo eso solo para mí, sino también para la pareja real!",
    "S1S4_2": "El carruaje debería ser el más rico que se haya hecho en el reino para mostrar el poder del rey y la riqueza de su tierra, debe ser una obra de arte y un lujo.",
    "S1S4_3": "La familia real tiene muchas cosas para llevar, ropa, regalos, etc. Así que necesito espacio para poner todo eso en el carruaje.",
    "S1S4_4": "Piensa en los caballos que arrastrarán el carruaje. Si quieres ir rápido, tiene que ser pequeño y ligero. De lo contrario, se cansarán rápidamente.",
    "S1S4_5": "Sería fantástico si el carruaje pudiera adaptarse a algunos de mis instrumentos médicos y poder organizar mis medicamentos. Podría tener todo a mi disposición en caso de necesidad.",
    "S1S4_6": "La pareja real tiene que comer, pero puede elegir quedarse en otros palacios o en las casas de los invitados. No hay necesidad de una mini cocina a bordo.",
    "S1S4_7": "El carruaje debe ser liviano y eficiente. No estás construyendo una torre que tenga que aguantar durante siglos, sino un carrito ambulante. Haz que sea liviano y ágil.",
    "S1S4_8": "El tiempo es dinero. Un rey y una reina no tienen tiempo que perder deambulando por ahí. Solo hazlo rápido.",
    "S1S4_9": "Haz que el carruaje sea cómodo porque las piedras del adoquín aquí son muy duras ... y los traseros del rey y la reina se resentirán ... te lo puedo asegurar",
    "S1S4_10": "El carruaje debe reflejar la importancia del papel del rey en todo el mundo y la historia del reino y, por lo tanto, estar cargado de símbolos históricos, el carruaje debería convertirse en un artefacto legendario.",
    "S1S4_11": "¡Fuera de mi camino, hay algunas personas trabajando aquí!",
    "S1S4_12": "No permitas que la familia real arruine el reino con este carruaje. Ya tienen mucho más de lo que nosotros, la gente, tenemos. Hazlo simple.",
    "S1S4_13": "El que viaja felizmente debe viajar ligero (Antoine de St Exupery)",
    "S1S4_14": "No tengo tiempo para discutir. Tengo carne que recoger.",
    "S1S5_1": "Ahora que ha reunido suficientes opiniones, puede regresar a su taller para comenzar a trabajar en su proyecto o continuar reuniéndose con otras personas.",
    "S2S0": "¡Éste es su taller! Basándose en lo que ha escuchado, es hora de tomar algunas decisiones sobre qué tipo de transporte piensa que se ajusta mejor a las necesidades del Rey y la Reina.",
    "S2L1": "Lento",
    "S2L2": "Rápido",
    "S2L3": "Tosco",
    "S2L4": "Bello",
    "S2L5": "Básico",
    "S2L6": "Lujoso",
    "S2L7": "Pequeño",
    "S2L8": "Grande",
    "S2L9": "Ligero",
    "S2L10": "¿El rey y la reina prefieren la velocidad alta o viajar más lento pero con seguridad a través de todo tipo de caminos?",
    "S2L11": "¿El rey y la reina preferirán un carruaje duradero o un carruaje lujoso?",
    "S2L12": "¿El rey y la reina preferirán un carruaje minimalista pero práctico o uno muy lujoso?",
    "S2L13": "¿El rey y la reina preferirán un carruaje pequeño y rápido o un carruaje cómodo más lento?",
    "S2L14": "¿El rey y la reina preferirán un carro ligero básico o uno muy robusto?",
    "S2L15": "Fuerte",
    "S2S1": "Parece que no ha tomado decisiones acertadas... Un carruaje mediano no se ajustará a las necesidades del Rey y la Reina. Tome decisiones reales.",
    "S2S2": "¡Qué carro tan prometedor! ¡Bien hecho!",
    "S3S1_1": "Antes de seguir adelante con nuestro plan, tal vez deberíamos considerar ver los carruajes de otros reyes y reinas. ¡Esto podría inspirarnos!",
    "S3S1_2": "El carruaje de la reina Patricia es el más rápido dentro del Reino pero a menudo falla y se rompe.",
    "S3S1_3": "El carruaje de la reina Mihaela es el más hermoso pero no muy conveniente... un poco pesado y una pesadilla para limpiar (el barro se atasca en todos los elementos decorativos de las paredes exteriores).",
    "S3S1_4": "El carruaje del rey Pablo es el más fuerte dentro del Reino. Sobrevivió a muy malos caminos e incluso a muchos ataques y tuvo éxito siempre en mantener a salvo al rey y la reina.",
    "S3S1_5": "El carruaje de la Reina Ana es el más cómodo. Incluso el asiento para el cochero está hecho de materiales muy suaves y cómodos. Hace que cada viaje sea muy placentero.",
    "S3S1_6": "El carruaje del rey Tharrenos es el más grande. Ofrece un gran espacio. Viajando con este carruaje uno se siente como viajar sin salir de su sala de estar.",
    "S3S3_1": "Espero que este pequeño recorrido por los carruajes de otros reyes y reinas le haya inspirado. ¡Ahora sigamos con los nuestros!",
    "S4S1_1": "Con toda la información que recogió de las personas que ha conocido, los carruajes existentes que ha visto y su propio punto de vista e intuición, ahora es el momento de empezar a prototipar el carro. ",
    "S4S2_1": "Su carruaje es demasiado barato. ¡Está construyendo el carruaje de la familia real! No es un carrito de comerciante!  ",
    "S4S2_2": "Su carruaje es tan simple que sólo le llevará un par de semanas construirlo. Podemos invertir más tiempo ya que tenemos 6 meses para entregarlo. Vamos a mejorar nuestro carro  ",
    "S4S2_3": "Su carruaje es demasiado pesado y lento. Los viajes se harán eternos.",
    "S4S2_4": "Su carruaje es demasiado rústico para un carruaje real, parece un carruaje de campesino.",
    "S4S2_5": "Tienes que hacer un carruaje no un carro. ¡Hágalo más sofisticado!  ",
    "S4S2_6": "Su carruaje es demasiado frágil. Se romperá en la primera piedra de adoquín que le golpee. ",
    "S4S2_7": "¡Estás arruinando el Reino!  Reconsidere su diseño eligiendo elementos menos costosos.  ",
    "S4S2_8": "La familia Real necesita el carruaje listo en 6 meses. Elija algunos elementos más simples para reducir el tiempo de construcción.  ",
    "S4S3_1": "Necesita mejorar su diseño antes de continuar.",
    "S4S3_2": "¡De acuerdo! ¡Procedamos con las pruebas!",
    "S5S0_1": "Ahora que su prototipo está listo, vamos a mostrarlo a algunas personas para ver lo que piensan de él antes de presentarlo a los reyes.",
    "S5S1_1": "Bien, me parece bastante fuerte. Debemos probarlo antes de mostrarselo al rey y la reina.  ",
    "S5S1_2": "Bien hecho. Mi amigo. Es un carruaje muy bonito. ¿pero crees que puede atravesar calles estrechas? Deberías intentarlo antes de entregarlo.  ",
    "S5S1_3": "No está mal, no está mal... ¿pero crees que es lo suficientemente lujoso si la pareja real tiene que ir a una ceremonia? Pregúnteselo a la gente antes de entregarlo al rey y la reina.  ",
    "S5S1_4": "Lo siento, no hay tiempo para charlar. ",
    "S5S1_5": "Tengo trabajo que hacer. Pregúntele a otra persona.  ",
    "S5S1_6": "¿Mmm?",
    "S5S1_7": "Basándose en los comentarios que acaba de recibir, ¿desea revisar su diseño o ignorar sus comentarios y mantener su diseño como es? ",
    "S5S2_1": "Ahora está listo para la prueba en el mundo real. ¿está listo para ver si su carruaje es lo suficientemente bueno ahora? Lleve el carruaje afuera y parése en el cruce de la carretera. Hay 3 caminos que puede elegir. Escoge uno de los 3 caminos.",
    "S5S2_2A": "Acabas de llegar a la ciudad con el carruaje y nadie se ha dado cuenta de tu llegada ... No es una buena señal. ¡El Carro Real debe ser notado por todo el mundo! ¡Las multitudes deberían estar reuniéndose a su alrededor! Deberías considerar hacerlo más llamativo ...",
    "S5S2_2": "Ha elegido que su carruaje sea seguido por artistas (músicos, artistas), banderas y animales bellos como elefantes, jirafas, camellos, avestruces... para ir al Congreso de Reyes y Reinas! Lo que es bueno es que esto no impacta el diseño de su carro sino que le permite presumir de carro temporalmente sin modificarlo ¡Bien hecho!",
    "S5S2_3A": "Acabas de llegar a la ciudad de tu viejo amigo el Señor Christophe. ¡Qué casualidad! Están planeando viajar a Portalona al día siguiente, al igual que tu carruaje. Deberías considerar compartirlo con ellos ...",
    "S5S2_3": "Ha elegido ahora diseñar el carro para que pueda ser compartido. ¡Felicitaciones! La mayoría de los carros están estacionados durante el 80% de su tiempo, por lo que compartir significa ahorrar. Recuerde también pensar en cómo dividir el tiempo de uso del carro.",
    "S5S2_4A": "Acabas de pasar el puente de Oslina ... ¡Emboscada! Una banda de ladrones! ¡Pero hurra! ¡Has logrado escapar! Deberías considerar proteger el carro ..",
    "S5S2_4": "¡Ahora ha elegido rodear su carruaje con soldados y armas para sobrellevar la guerra! Lo bueno es que no tiene que cambiar nada sobre el diseño de su carro. Esto le permite responder temporalmente a esta necesidad excepcional con poco esfuerzo. ¡Bien hecho!",
    "S5S2B": "Acaban de aparecer nuevas opciones en el taller, vuelve para descubrirlas.",
    "S5S2C": "Ahora que has aumentado tu carruaje, llévalo fuera para probarlo.",
    "S6S1_1": "¡Es el gran día que hemos estado esperando! Es hora de que presentar nuestro carruaje al Rey y a la Reina.",
    "S6S1_2": "¡Bien hecho! Ha hecho un trabajo fantástico. Estoy muy contenta con el resultado.",
    "S6S1_3": "¡Sí, este carruaje es perfecto!",
    "S6S2_1": "Muchas gracias... ¿pero podría hacerlo rosa?",
    "S6S2_2": "Gracias... ¿pero lo podría hacer del color del arco iris?",
    "S6S2_3": "Es fántastico, pero me gustaría aún más con alas.",
    "S6S2_4": "Me gusta mucho, ¿pero lo podría cubrir de plumas?",
    "S6S3_1": "¡Ha hecho un trabajo increíble! ¡Esto es una obra maestra! ¡Puede celebrarlo! Todo el Reino está agradecido. ¡no sé cuáles son tus planes para el futuro, pero no pierda esa creatividad suya!",
    "B1": "Mente creativa",
    "B2": "Pensamiento crítico",
    "B3": "Oyente",
    "B4": "Nunca te rindes",
    "B5": "Solucionador/a de problemas",
    "M1": "Ahora puedes seguir con el próximo paso",
    "M2": "Selecciona un/a personaje para recibir más mensajes",
    "M3": "Selecciona un/a personaje",
    "next.page": "Próxima página",
    "previous.page": "Pàgina anterior",
    "see.result": "Comprueva los resultados",
    "next.step": "Siguiente paso",
    "start": "Comienza",
    "B6": "Cierra",
    "B7": "Pista",
    "B8": "Ir al taller",
    "B9": "Escribe tu nombre...",
    "B10": "Comienza el juego",
    "B11": "Carga el juego",
    "S4L1": "Ruedas",
    "S4L2": "Chasis",
    "S4L3": "Asiento del conductor",
    "S4L4": "Asientos interiores",
    "S4L5": "Carrocería",
    "S4L6": "Equipaje",
    "N1L1": "Construye el mejor carruaje práctico y atractivo para la familia real",
    "N1L2": "Personajes",
    "N1L3": "Indicadores",
    "N1L4": "Carruajes",
    "N1L5": "Ejemplos",
    "N1L6": "Tu carruaje",
    "N1L7": "Disrupciones",
    "N1L8": "Medallas",
    "N1L9": "La misión",
    "S6A1": "¡Gracias mi reina! ¡Realmente disfruté trabajando en esto! Y he tenido muchas otras ideas al tratar de diseñar el mejor carro, ¿quizás algunas les serían útiles?",
    "S6A2": "Adelante!",
    "S6A3": "Bien, tal vez podríamos hacer el carro más...",
    "S6A4": "hermoso, rodeando el carruaje con animadores (músicos, artistas), banderas y animales, ¡para ir al congreso de reyes y reinas! Apuesto a que todos quedarán muy impresionados.",
    "S6A5": "Respetuoso con el medio ambiente, diseñando el carro para que se pueda compartir. La mayoría de los carruajes están estacionados el 80% de su tiempo. ¡Compártanlo!",
    "S6A6": "¿Tiene alguna sugerencia para mí?",
    "S6A7": "Sí mi rey, quizás podría proteger su carruaje preparándolo para la guerra. No es suficiente con una carrocería fuerte, debe rodear su carruaje con soldados y escudos. Seguramente impresionará a sus posibles atacantes.",    
}