export const data = {
    "S1S1_1": "Bonjour mon ami!",
    "S1S1_2": "Bonjour.",
    "S1S1_3": "Je suis le messager du roi. Nous avons une mission à vous confier. Le roi a entendu dire que vous étiez le meilleur artisan du royaume et que vous trouviez des solutions à toutes sortes de problèmes. Est-ce vrai?",
    "S1S1_4": "Et bien, j'essaye de faire de mon mieux.",
    "S1S1_5": "Ne soyez pas si humble. Si cela est vrai, alors prenez vos affaires et suivez moi. Nous allons à la Cité Royale de Lalandie, Empathia!",
    "S1S2_1": "Ah je suis content que vous ayez accepté mon invitation. Je suis le roi de Lalandia et il me faut un nouveau carrosse pour voyager à travers mon royaume. On m'a dit que vous étiez le meilleur artisan/designer de tout le royaume. Donc ma mission, si vous l'acceptez, est de me construire le meilleur carrosse au monde.",
    "S1S2_2": "Et moi, je suis la reine de Lalandia. J'utiliserai aussi ce carrosse pour voyager à travers le royaume. Il faut qu'il soit à la fois pratique et, bien-sûr, le plus beau du monde.",
    "S1S2_3": "Oui, oui. C'est exactement ce qu'il nous faut. Et nous en aurons besoin dans 6 mois car nous devons nous rendre au Conseil des Grands Rois où tous les Rois du Nord se réunissent. Alors, qu'en dites vous, vous acceptez?",
    "S1S2_4": "Ma reine, mon roi, c'est un honneur d'accepter cette mission. Je releverai donc le défi. Afin de concevoir ce carrosse, j'aurais beaucoup de questions à vous poser pour bien comprendre vos besoins.",
    "S1S2_5": "Mon garçon/ma fille, vous les avez déjà. Nous venons juste de vous les dire. Maintenant en avant! La reine et moi-même avons invité le Prince de la Mer du Sud, nous n'avons plus le temps pour discuter d'avantage. Bonne chance!",
    "S1S2_6": "Mais quel type de carrosse dois-je concevoir? Quels devraient être ses différentes fonctions? Je n'ai aucun idée des réels besoins du roi et de la reine. Tout ceci est bien flou.",
    "S1S3_1": "Mais à quoi ressemble le meilleur carrosse, le plus pratique et le plus beau du monde? Vous allez entrer dans un monde et rencontrer pleins de personnages. Chacun vous dira à quoi le carrosse devrait ressembler selon eux.",
    "S1S3_2": "Vous semblez bien perdu mon garçon/ma fille.",
    "S1S3_3": "Eh bien, un peu, oui. Le roi et la reine viennent juste de me confier la mission de construire leur nouveau carrosse. Mais j'ai besoin de plus d'informations pour bien le concevoir. A quoi va-t-il leur servir? De quoi ont-ils besoin? Sur quels types de routes ont-ils l'habitude de voyager? Quelle taille devrait-il avoir? Quelles devraient être ses fonctions? Ils sont restés très flous dans leur commande.",
    "S1S3_4": "Mon ami.e, vous devez fabriquer un carrosse solide et très résistant! La famille royale doit pouvoir voyager en toute sécurité. Et pas besoin de coquetterie, y'a de la beauté dans les choses brutes et simples! Mais je vous conseille d'aller faire un tour et d'aller collecter d'autres points de vues.",
    "S1S4_1": "Les longs voyages peuvent être épuisants. Le carrosse doit être confortable. Et je ne dis pas ça juste pour moi mais aussi pour le couple royal!",
    "S1S4_2": "Ce carrosse doit être le plus richement décoré du royaume pour montrer le pouvoir du roi et la richesse de son pays. Ce carosse doit être un véritable chef d'oeuvre! Du luxe!",
    "S1S4_3": "La famille royale a beaucoup d'affaires à transporter, entre les vêtements, les cadeaux, etc. J'ai besoin de place pour mettre tout ça dans le carrosse!",
    "S1S4_4": "Pense aux chevaux qui tirent le carrosse. Plus le carrosse est petit et léger, plus ils pourront aller vite. Sinon ils vont s'épuiser très rapidement.",
    "S1S4_5": "Ce serait vraiment bien si je pouvais stocker quelques médicaments et du matériel médical dans le carrosse. Comme ça j'aurais tout à portée de main en cas de besoin.",
    "S1S4_6": "Le couple royal doit manger, mais il peut très bien choisir de loger dans un de ses palais ou dans des chambres d'hôtes. Pas besoin d'une cuisine à bord.",
    "S1S4_7": "Le carrosse doit être léger et efficace. Il ne s'agit pas de bâtir une tour pour les siècles à venir mais un véhicule. Fais-le léger et agile.",
    "S1S4_8": "Le temps c'est de l'argent mon ami.e.! Un roi et une reine n'ont pas de temps à perdre. Faite un bolide.",
    "S1S4_9": "Fais un carrosse confortable car les pavés sont très durs… sinon le roi et la reine auront bien mal aux derrières, je peux te l'assurer!",
    "S1S4_10": "Le carrosse doit refléter l'importance du rôle du Roi dans le monde et à travers l'Histoire du Royaume. Il doit donc être empli de symboles historiques. Ce carrosse doit devenir légendaire!",
    "S1S4_11": "Hors de mon chemin, y'en a qui travaillent ici!",
    "S1S4_12": "Ne laisse pas la famile royale ruiner le Royaume avec ce carrosse. Ils ont déjà bien plus que nous le peuple. Fais simple.",
    "S1S4_13": "Pour voyager heureux, voyagez léger. (Antoine de St-Exupéry)",
    "S1S4_14": "Je n'ai pas l'temps de discuter. J'ai du gibier à chasser.",
    "S1S5_1": "Maintenant que tu as collecté suffisament d'avis, tu peux soit retourner à l'atelier pour commencer le projet de carrosse, soit continuer à rencontrer d'autres personnes.",
    "S2S0": "Bienvenue dans ton atelier! Il est désormais temps de se lancer! En te basant sur ce que tu as entendu, tu dois concevoir le carrosse le plus adapté aux besoins du Roi et de la Reine.",
    "S2L1": "Lent",
    "S2L2": "Rapide",
    "S2L3": "Brut",
    "S2L4": "Élégant",
    "S2L5": "Confort de base",
    "S2L6": "Confort luxueux",
    "S2L7": "Petit",
    "S2L8": "Large",
    "S2L9": "Léger",
    "S2L10": "Le roi et la reine préfèront-ils plutôt voyager très vite ou plus lentemps mais en étant sûrs d'arriver à bon port quelque soit l'état de la route?",
    "S2L11": "Le roi et la reine préféreront-il plutôt un carrosse durable ou un véhicule très élégant?",
    "S2L12": "Le roi et la reine préféreront-ils plutôt un carrosse minimaliste mais pratique ou un carosse très luxueux?",
    "S2L13": "Le roi et la reine préféreront-ils plutôt un petit carosse rapide ou un carrosse plus lent mais très confortable?",
    "S2L14": "Le roi et la reine vont-ils préférer plutôt un carosse simple et léger ou un carrosse plus lourd car solide?",
    "S2L15": "Solide",
    "S2S1": "Mon ami.e, on dirait que tu n'as pas pris de vraie décision. Un carrosse de taille moyenne ne convient pas aux besoins du Roi et de la Reine. Fais de vrais choix.",
    "S2S2": "Quel carrosse prometteur! Beau travail!",
    "S3S1_1": "Avant de continuer avec cette idée, peut-être devrions nous jeter un oeil aux carrosse des autres rois et reines. Ca nous donnera surement de l'inspiration.",
    "S3S1_2": "Le carrosse de la Reine Patricia est le plus rapide du royaume mais il est fragile et casse souvent.",
    "S3S1_3": "Le carrosse de la Reine Mihaela est le plus beau mais il n'est pas très pratique, il est un peu lourd et c'est un cauchemar quand il faut le nettoyer (la boue reste coller dans les décors des paroies extérieures).",
    "S3S1_4": "Le carrosse du Roi Pablo est le plus robuste du royaume. Il résiste bien aux mauvaises routes et mêmes aux attaques! Le Roi et la Reine ont toujours été en sécurité dans ce carrosse! ",
    "S3S1_5": "Le carrosse de la Reine Ana est le plus confortable. Même le siège du cocher est doux et confortable! Dans ce carosse, tous les voyages deviennent agréables!",
    "S3S1_6": "Le carrosse du Roi Tharrenos est le plus grand. Il est tellement spacieux qu'on dirait qu'on voyage sans même sortir de son salon.",
    "S3S3_1": "J'espère que ce petit tour des carrosse des autres rois et reines t'as inspiré. Allez! Remettons nous au travail!",
    "S4S1_1": "Avec toutes les informations que tu as collectées, les différentes personnes que tu as rencontrées et les carrosse que tu as vu, et ton propre point de vue et intuition, il est désormais temps de faire un prototype du carrosse.",
    "S4S2_1": "Ton carrosse n'est pas d'assez bonne qualité! C'est un carosse royal que tu construis pas un wagon de marchant!",
    "S4S2_2": "Ton carrosse est tellement simple que ça ne prendra que quelques semaines pour le construire. Nous avons 6 mois pour le livrer, donc prenons le temps de l'améliorer.",
    "S4S2_3": "Ton carrosse est bien trop lourd et lent. Les voyages vont prendre une éternité.",
    "S4S2_4": "Ton carrosse est trop brut pour un carrosse royal, on dirait une charette de paysan.",
    "S4S2_5": "Il faut que tu fasses un carrosse pas une roulotte. Fais-le plus sophistiqué.",
    "S4S2_6": "Ton carrosse est bien trop fragile comme ça. Au moindre choc il va casser.",
    "S4S2_7": "Tu vas ruiner le Royaume! Revoie ton design et choisis des équipements moins chers.",
    "S4S2_8": "La famille royale a besoin du carrosse dans 6 mois. Choisis des éléments plus simples pour que la construction soit plus rapide.",
    "S4S3_1": "Tu dois encore améliorer ton design avant de continuer.",
    "S4S3_2": "C'est bon! Allons le tester!",
    "S5S0_1": "Maintenant que ton prototype est prêt, montrons le à des gens pour voir ce qu'ils en pensent avant de le présenter au Roi.",
    "S5S1_1": "Eh bien, ça me paraît plutôt solide. On devrait faire un essai avant de le donner au Roi et à la Reine.",
    "S5S1_2": "Bon travail mon ami. Quel beau carrosse. Mais est-ce qu'il passe dans les rues étroites? Il faudrait vérifier ça avant de le livrer au Roi et à la Reine.",
    "S5S1_3": "Pas mal, je dirais même, pas mal du tout. Mais est-ce suffisament rafiné si le couple royal devait aller à une cérémonie? Tu devrais demander aux gens leur avis avant de le présenter au Roi et à la Reine.",
    "S5S1_4": "Désolé, j'ai pas le temps de papoter.",
    "S5S1_5": "J'ai du travail. Demande à quelqu'un d'autre.",
    "S5S1_6": "Hm?",
    "S5S1_7": "Maintenant que tu as eu ce retour, veux-tu modifer ton design ou ignorer ce retour et garder ton design tel quel?",
    "S5S2_1": "Maintenant tu es prêt pour un test en vrai. Paré pour voir si ton carrosse tiens la route? Tu vas prendre le carrosse. Arrivé.e au croisement de 3 chemins, choisis-en un.",
    "S5S2_2A": "Tu arrives avec ton carrosse dans la ville mais personne ne remarque ton arrivée... Ca, ce n'est pas bon signe. Le Carrosse Royal doit attirer l'attention de tout le monde! Des foules devraient s'attrouper autour! Tu devrais penser à le rendre plus extraordinaire...",
    "S5S2_2": "Tu as choisis d'entourer le carrosse de divertissements (musiciens, artistes), drapeaux et d'animaux exotiques éléphants/giraffe/chameau/autruche, pour aller au congrès des Rois et Reines! Le point positif de ce choix c'est qu'il permet de répondre temporairement au besoin exceptionnel d'impressionner les gens et les autres rois et reines. Bien joué!",
    "S5S2_3A": "Tu arrives dans la ville de ton vieil ami Lord Christophe. Quelle coïncidence! Chacun de vous pensiez vous rendre à Portalona le lendemain. Tu devrais envisager le co-carrossage...",
    "S5S2_3": "Tu as choisis un design de carrosse pour le partage et le covoiturage. Félicitations! La plupart des carrosse sont garés 80% de leur temps. Partager c'est faire attention aux autres. Souviens-toi de penser à comment répartir le temps d'utilisation du carrosse.",
    "S5S2_4A": "Tu passes le pont d'Oslina... Une embuscade! Une bande de brigands! Mais hourra! Tu réussis de justesse à t'échapper! Tu devrais envisager de protéger d'avantage le carrosse...",
    "S5S2_4": "Tu as choisi d'entourer le carrosse de soldats et d'armes pour faire face à la guerre! Ce qui est bien c'est qu'il n'y a rien a changer au design du carrosse. Ca permet de répondre temporairement à ce besoin exceptionnel avec peu d'efforts. Bien joué!",
    "S5S2B": "De nouvelles options viennent juste d'apparaître dans ton atelier. Retournes y pour les découvrir.",
    "S5S2C": "Maintenant que tu as amélioré ton carrosse, sors le pour faire un nouveau test.",
    "S6S1_1": "Le jour que nous avions tant attendu est arrivé! C'est le moment de présenter le carrosse au Roi et à la Reine.",
    "S6S1_2": "Bravo! Vous avez fait un travail remarquable. Je suis très contente.",
    "S6S1_3": "Oui, ce carrosse est parfait!",
    "S6S2_1": "Merci beaucoup. Juste une chose... vous pourriez le faire rose?",
    "S6S2_2": "J'adore, mais est-ce qu'il pourrait avoir les couleurs de l'arc-en-ciel?",
    "S6S2_3": "Ce carrosse est incroyable mais pourriez-vous lui rajouter des ailes?",
    "S6S2_4": "J'aime beaucoup mais pourrait-on le recouvrir de plumes?",
    "S6S3_1": "Mon ami vous avez fait un travail fantastique! C'est un véritable chef-d'oeuvre! Vous pouvez être fièr.e de vous. Le royaume entier vous remercie. Je ne connais pas vos plans pour l'avenir, mais gardez votre esprit curieux et créatif!",
    "B1": "Esprit créatif",
    "B2": "Esprit critique",
    "B3": "Bonne écoute",
    "B4": "Persévérant",
    "B5": "Solutionneur",
    "M1": "Maintenant tu peux passer à l'étape suivante",
    "M2": "Cliques sur un des personnages pour entendre son avis",
    "M3": "Cliques sur un des personnages",
    "next.page": "Page suivante",
    "previous.page": "Page précédante",
    "see.result": "Voir le résultat",
    "next.step": "Étape suivante",
    "start": "Démarrer",
    "B6": "Fermer",
    "B7": "Hint",
    "B8": "Go to the workshop",
    "B9": "",
    "S4L1": "Roues",
    "S4L2": "Châssis",
    "S4L3": "Siège conducteur",
    "S4L4": "Sièges intérieurs",
    "S4L5": "Murs",
    "S4L6": "Rangement",
    "N1L1": "Construis un carrosse pour la famille royale qui soit le meilleur, le plus pratique et le plus beau",
    "N1L2": "Personnages",
    "N1L3": "Indicateurs",
    "N1L4": "Carrosses",
    "N1L5": "Exemples",
    "N1L6": "Ton carrosse",
    "N1L7": "Perturbations",
    "S6A1": "Merci ma reine! J'ai beaucoup aimé travailler sur ce projet de carrosse. D'ailleurs j'ai plusieurs idées pour rendre le carrosse encore meilleur. Ca vous intéresse?",
    "S6A2": "Allez-y!",
    "S6A3": "Et bien, vous pourriez rendre le carrosse",
    "S6A4": "encore plus beau si vous l'entouriez de saltimbanques, musiciens et artistes, de drapeaux et d'animaux exotiques, d'éléphants, de giraffes, de dromadaires, d'autruches. Imaginez l'impression que vous feriez au Conseil des rois et reines!",
    "S6A5": "plus durable si vous l'aménagez pour le partage. La plupart des carrosses sont garés 80% du temps! Partagez votre carrosse! ",
    "S6A6": "Et des suggestions pour moi?",
    "S6A7": "Oui mon roi. Vous pourriez protéger votre carrosse en l'équippant pour la guerre. Des parois plus épaisses ne suffiront pas, entourez votre carrosse de soldats, de boucliers et de piques. Ceux qui veulent vous attaquer y réfléchiront à deux fois!",
    "N1L8": "",
    "N1L9": "",
    }