export const data = {
    "S1S1_1": "Bonjour mon ami !",
    "S1S1_2": "Bonjour.",
    "S1S1_3": "Je suis le messager du roi. Nous avons une mission à vous confier. Le roi a entendu dire que vous étiez le meilleur artisan du royaume et que vous trouviez des solutions à toutes sortes de problèmes. Est-ce vrai ?",
    "S1S1_4": "Et bien, j'essaye de faire de mon mieux.",
    "S1S1_5": "Ne soyez pas si humble. Si cela est vrai, alors prenez vos affaires et suivez moi. Nous allons à la Cité Royale de Lalandie, Empathia !",
    "S1S2_1": "Ah je suis content que vous ayez accepté mon invitation. Je suis le roi de Lalandia et il me faut un nouveau carosse pour voyager à travers mon royaume. On m’a dit que vous étiez le meilleur artisan/designer de tout le royaume. Donc ma mission, si vous l’acceptez, est de me construire le meilleur carosse au monde.",
    "S1S2_2": "Et moi, je suis la reine de Lalandia. J’utiliserai aussi ce carosse pour voyager à travers le royaume. Il faut qu'il soit à la fois pratique et, bien-sûr, le plus beau du monde.",
    "S1S2_3": "Oui, oui. C’est exactement ce qu’il nous faut. Et nous en aurons besoin dans 6 mois car nous devons nous rendre au Conseil des Grands Rois où tous les Rois du Nord se réunissent. Alors, qu'en dites vous, vous acceptez ?",
    "S1S2_4": "Ma reine, mon roi, c'est un honneur d’accepter cette mission. Je releverai donc le défi. Afin de concevoir ce carrosse, j’aurais beaucoup de questions à vous poser pour bien comprendre vos besoins.",
    "S1S2_5": "Mon garçon/ma fille, vous les avez déjà. Nous venons juste de vous les dire. Maintenant en avant ! La reine et moi-même avons invité le Prince de la Mer du Sud, nous n’avons plus le temps pour discuter d’avantage. Bonne chance !",
    "S1S2_6": "Mais quel type de carosse dois-je concevoir ? Quels devraient être ses différentes fonctions ? Je n’ai aucun idée des réels besoins du roi et de la reine. Tout ceci est bien flou.",
    "S1S3_1": "Mais à quoi ressemble le meilleur carosse, le plus pratique et le plus beau du monde ? Vous allez entrer dans un monde et rencontrer pleins de personnages. Chacun vous dira à quoi le carosse devrait ressembler selon eux.",
    "S1S3_2": "Vous semblez bien perdu mon garçon/ma fille.",
    "S1S3_3": "Eh bien, un peu, oui. Le roi et la reine viennent juste de me confier la mission de construire leur nouveau carosse. Mais j’ai besoin de plus d’informations pour bien le concevoir. A quoi va-t-il leur servir ? De quoi ont-ils besoin ? Sur quels types de routes ont-ils l’habitude de voyager ? Quelle taille devrait-il avoir ? Quelles devraient être ses fonctions ? Ils sont restés très flous dans leur commande.",
    "S1S3_4": "“Mon ami.e, vous devez fabriquer un carosse solide et très résistant ! La famille royale doit pouvoir voyager en toute sécurité. Et pas besoin de coquetterie, y'a de la beauté dans les choses brutes et simples! Mais je vous conseille d'aller faire un tour et d'aller collecter d'autres points de vues.”",
    "S1S4_1": "“Les longs voyages peuvent être épuisants. Le carosse doit être confortable. Et je ne dis pas ça juste pour moi mais aussi pour le couple royal !”",
    "S1S4_2": "“Ce carosse doit être le plus richement décoré du royaume pour montrer le pouvoir du roi et la richesse de son pays. Ce carosse doit être un véritable chef d’oeuvre ! Du luxe !",
    "S1S4_3": "“La famille royale a beaucoup d’affaires à transporter, entre les vêtements, les cadeaux, etc. J’ai besoin de place pour mettre tout ça dans le carosse!”",
    "S1S4_4": "“Pense aux chevaux qui tirent le carosse. Plus le carosse est petit et léger, plus ils pourront aller vite. Sinon ils vont s’épuiser très rapidement.”",
    "S1S4_5": "“Ce serait vraiment bien si je pouvais stocker quelques médicaments et du matériel médical dans le carosse. Comme ça j’aurais tout à portée de main en cas de besoin.“",
    "S1S4_6": "“Le couple royal doit manger, mais il peut très bien choisir de loger dans un de ses palais ou dans des chambres d’hôtes. Pas besoin d’une cuisine à bord.”",
    "S1S4_7": "“Le carosse doit être léger et efficace. Il ne s’agit pas de bâtir une tour pour les siècles à venir mais un véhicule. Fais-le léger et agile.”",
    "S1S4_8": "“Le temps c’est de l’argent mon ami.e.! Un roi et une reine n’ont pas de temps à perdre. Faite un bolide.”",
    "S1S4_9": "“Fais un carosse confortable car les pavés sont très durs… sinon le roi et la reine auront bien mal aux derrières, je peux te l'assurer!”",
    "S1S4_10": "“Le carosse doit refléter l’importance du rôle du Roi dans le monde et à travers l’Histoire du Royaume. Il doit donc être empli de symboles historiques. Ce carosse doit devenir légendaire!”",
    "S1S4_11": "“Hors de mon chemin, y’en a qui travaillent ici !”",
    "S1S4_12": "“Ne laisse pas la famile royale ruiner le Royaume avec ce carosse. Ils ont déjà bien plus que nous le peuple. Fais simple.”",
    "S1S4_13": "“Pour voyager heureux, voyagez léger.” (Antoine de St-Exupéry)",
    "S1S4_14": "“Je n’ai pas l’temps de discuter. J’ai du gibier à chasser.”",
    "S1S5_1": "Maintenant que tu as collecté suffisament d’avis, tu peux soit retourner à l’atelier pour commencer le projet de carosse, soit continuer à rencontrer d’autres personnes.",
    "S2S0": "Bienvenue dans ton atelier ! Il est désormais temps de se lancer! En te basant sur ce que tu as entendu, tu dois concevoir le carosse le plus adapté aux besoins du Roi et de la Reine.",
    "S2S1": "Mon ami.e, on dirait que tu n’as pas pris de vraie décision. Un carosse de taille moyenne ne convient pas aux besoins du Roi et de la Reine. Fais de vrais choix.",
    "S2S2": "Quel carosse prometteur ! Beau travail !",
    "S3S1_1": "Avant de continuer avec cette idée, peut-être devrions nous jeter un oeil aux carosses des autres rois et reines. Ca nous donnera surement de l’inspiration.",
    "S3S1_2": "Le carosse de la Reine Patricia est le plus rapide du royaume mais il est fragile et casse souvent.",
    "S3S1_3": "Le carosse de la Reine Mihaela est le plus beau mais il n'est pas très pratique, il est un peu lourd et c’est un cauchemar quand il faut le nettoyer (la boue reste coller dans les décors des paroies extérieures).",
    "S3S1_4": "Le carosse du Roi Pablo est le plus robuste du royaume. Il résiste bien aux mauvaises routes et mêmes aux attaques ! Le Roi et la Reine ont toujours été en sécurité dans ce carosse! ",
    "S3S1_5": "Le carosse de la Reine Ana est le plus confortable. Même le siège du cocher est doux et confortable! Dans ce carosse, tous les voyages deviennent agréables !",
    "S3S1_6": "Le carosse du Roi Tharrenos est le plus grand. Il est tellement spacieux qu'on dirait qu’on voyage sans même sortir de son salon.",
    "S3S3_1": "J’espère que ce petit tour des carosses des autres rois et reines t’as inspiré. Allez ! Remettons nous au travail !",
    "S4S1_1": "Avec toutes les informations que tu as collectées, les différentes personnes que tu as rencontrées et les carosses que tu as vu, et ton propre point de vue et intuition, il est désormais temps de faire un prototype du carosse.",
    "S4S2_1": "Ton carosse n’est pas d'assez bonne qualité ! C'est un carosse royal que tu construis pas un wagon de marchant !",
    "S4S2_2": "Ton carosse est tellement simple que ça ne prendra que quelques semaines pour le construire. Nous avons 6 mois pour le livrer, donc prenons le temps de l'améliorer.",
    "S4S2_3": "Ton carosse est bien trop lourd et lent. Les voyages vont prendre une éternité.",
    "S4S2_4": "Ton carosse est trop brut pour un carosse royal, on dirait une charette de paysan.",
    "S4S2_5": "Il faut que tu fasses un carosse pas une roulotte. Fais-le plus sophistiqué.",
    "S4S2_6": "Ton carosse est bien trop fragile comme ça. Au moindre choc il va casser.",
    "S4S2_7": "Tu vas ruiner le Royaume ! Revoie ton design et choisis des équipements moins chers.",
    "S4S2_8": "La famille royale a besoin du carosse dans 6 mois. Choisis des éléments plus simples pour que la construction soit plus rapide.",
    "S4S3_1": "Tu dois encore améliorer ton design avant de continuer.",
    "S4S3_2": "C'est bon ! Allons le tester !",
    "S5S0_1": "Maintenant que ton prototype est prêt, montrons le à des gens pour voir ce qu’ils en pensent avant de le présenter au Roi.",
    "S5S1_1": "Eh bien, ça me paraît plutôt solide. On devrait faire un essai avant de le donner au Roi et à la Reine.",
    "S5S1_2": "Bon travail mon ami. Quel beau carosse. Mais est-ce qu’il passe dans les rues étroites ? Il faudrait vérifier ça avant de le livrer au Roi et à la Reine.",
    "S5S1_3": "Pas mal, je dirais même, pas mal du tout. Mais est-ce suffisament rafiné si le couple royal devait aller à une cérémonie ? Tu devrais demander aux gens leur avis avant de le présenter au Roi et à la Reine.",
    "S5S1_4": "‘Désolé, j'ai pas le temps de papoter.”",
    "S5S1_5": "“J’ai du travail. Demande à quelqu’un d’autre.”",
    "S5S1_6": "“Hm ?”",
    "S5S1_7": "Maintenant que tu as eu ce retour, veux-tu modifer ton design ou ignorer ce retour et garder ton design tel quel ?",
    "S5S2_1": "Maintenant tu es prêt pour un test en vrai. Paré pour voir si ton carosse tiens la route ? Tu vas prendre le carosse. Arrivé au croisement de 3 chemins, choisis-en un.",
    "S5S2_2": "Tu as choisis d’entourer le carosse de divertissements (musiciens, artistes, soldats), drapeaux et d’animaux exotiques éléphants/giraffe/chameau/autruche, pour aller au congrès des Rois et Reines ! Le point positif de ce choix c’est qu’il permet de répondre temporairement au besoin exceptionnel d’impressionner les gens et les autres rois et reines. Bien joué !",
    "S5S2_3": "Tu as choisis un design de carosse pour le partage et le covoiturage. Félicitations ! La plupart des carosses sont garés 80% de leur temps. Partager c’est faire attention aux autres. Souviens-toi de penser à comment répartir le temps d’utilisation du carosse.",
    "S5S2_4": "Tu as choisi d’entourer le carosse de soldats et d’armes pour faire face à la guerre ! Ce qui est bien c’est qu’il n’y a rien a changer au design du carosse. Ca permet de répondre temporairement à ce besoin exceptionnel avec peu d’efforts. Bien joué !",
    "S6S1_1": "Le jour que nous avions tant attendu est arrivé ! C’est le moment de présenter le carosse au Roi et à la Reine.",
    "S6S1_2": "Bravo ! Vous avez fait un travail remarquable. Je suis très contente.",
    "S6S1_3": "Oui, ce carosse est parfait !",
    "S6S2_1": "Merci beaucoup. Juste une chose... vous pourriez le faire rose ?",
    "S6S2_2": "J’adore, mais est-ce qu’il pourrait avoir les couleurs de l’arc-en-ciel ?",
    "S6S2_3": "Ce carosse est incroyable mais pourriez-vous lui rajouter des ailes ?",
    "S6S2_4": "J’aime beaucoup mais pourrait-on le recouvrir de plumes ?",
    "S6S3_1": "Mon ami vous avez fait un travail fantastique ! C’est un véritable chef-d’oeuvre ! Vous pouvez être fièr.e de vous. Le royaume entier vous remercie. Je ne connais pas vos plans pour l’avenir, mais gardez votre esprit curieux et créatif !",
}