export const data = {
    "S1S1_1": "Bonjour mon ami !",
    "S1S1_2": "Bonjour.",
    "S1S1_3": "Je suis le messager du roi. Nous avons une mission \u00e0 vous confier. Le roi a entendu dire que vous \u00e9tiez le meilleur artisan du royaume et que vous trouviez des solutions \u00e0 toutes sortes de probl\u00e8mes. Est-ce vrai ?",
    "S1S1_4": "Et bien, j'essaye de faire de mon mieux.",
    "S1S1_5": "Ne soyez pas si humble. Si cela est vrai, alors prenez vos affaires et suivez moi. Nous allons \u00e0 la Cit\u00e9 Royale de Lalandie, Empathia !",
    "S1S2_1": "Ah je suis content que vous ayez accept\u00e9 mon invitation. Je suis le roi de Lalandia et il me faut un nouveau carrosse pour voyager \u00e0 travers mon royaume. On m\u2019a dit que vous \u00e9tiez le meilleur designer de tout le royaume. Donc votre mission, si vous l\u2019acceptez, est de me construire le meilleur carrosse au monde.",
    "S1S2_2": "Et moi, je suis la reine de Lalandia. J\u2019utiliserai aussi ce carrosse pour voyager \u00e0 travers le royaume. Il faut qu'il soit \u00e0 la fois pratique et, bien-s\u00fbr, le plus beau du monde.",
    "S1S2_3": "Oui, oui. C\u2019est exactement ce qu\u2019il nous faut. Et nous en aurons besoin dans 6 mois car nous devons nous rendre au Conseil des Grands Rois o\u00f9 tous les Rois du Nord se r\u00e9unissent. Alors, qu'en dites vous, vous acceptez ?",
    "S1S2_4": "Ma reine, mon roi, c'est un honneur d\u2019accepter cette mission. Je releverai donc le d\u00e9fi. Afin de concevoir ce carrosse, j\u2019aurais beaucoup de questions \u00e0 vous poser pour bien comprendre vos besoins.",
    "S1S2_5": "Mon ami.e, vous les avez d\u00e9j\u00e0. Nous venons juste de vous les dire. Maintenant en avant ! La reine et moi-m\u00eame avons invit\u00e9 le Prince de la Mer du Sud, nous n\u2019avons plus le temps pour discuter davantage. Bonne chance !",
    "S1S2_6": "Mais quel type de carrosse dois-je concevoir ? Quelles devraient \u00eatre ses diff\u00e9rentes fonctions ? Je n\u2019ai aucune id\u00e9e des r\u00e9els besoins du roi et de la reine. Tout ceci est bien flou.",
    "S1S3_1": "Mais \u00e0 quoi ressemble le meilleur carrosse, le plus pratique et le plus beau du monde ? Vous allez entrer dans un monde et rencontrer pleins de personnages. Chacun vous dira \u00e0 quoi le carrosse devrait ressembler selon eux.",
    "S1S3_2": "Vous semblez perdu.",
    "S1S3_3": "Eh bien, un peu, oui. Le roi et la reine viennent juste de me confier la mission de construire leur nouveau carrosse. Mais j\u2019ai besoin de plus d\u2019informations pour bien le concevoir. A quoi va-t-il leur servir ? De quoi ont-ils besoin ? Sur quels types de routes ont-ils l\u2019habitude de voyager ? Quelle taille devrait-il avoir ? Quelles devraient \u00eatre ses fonctions ? Ils sont rest\u00e9s tr\u00e8s flous dans leur commande.",
    "S1S3_4": "Mon ami.e, vous devez fabriquer un carrosse solide et tr\u00e8s r\u00e9sistant ! La famille royale doit pouvoir voyager en toute s\u00e9curit\u00e9. Et pas besoin de coquetterie, y'a de la beaut\u00e9 dans les choses brutes et simples! Mais je vous conseille d'aller faire un tour et d'aller collecter d'autres points de vues.",
    "S1S4_1": "Les longs voyages peuvent \u00eatre \u00e9puisants. Le carrosse doit \u00eatre confortable. Et je ne dis pas \u00e7a juste pour moi mais aussi pour le couple royal !",
    "S1S4_2": "Ce carrosse doit \u00eatre le plus richement d\u00e9cor\u00e9 du royaume pour montrer le pouvoir du roi et la richesse de son pays. Ce carosse doit \u00eatre un v\u00e9ritable chef d\u2019oeuvre ! Du luxe !",
    "S1S4_3": "La famille royale a beaucoup d\u2019affaires \u00e0 transporter, entre les v\u00eatements, les cadeaux, etc. J\u2019ai besoin de place pour mettre tout \u00e7a dans le carrosse!",
    "S1S4_4": "Pense aux chevaux qui tirent le carrosse. Plus le carrosse est petit et l\u00e9ger, plus ils pourront aller vite. Sinon ils vont s\u2019\u00e9puiser tr\u00e8s rapidement.",
    "S1S4_5": "Ce serait vraiment bien si je pouvais stocker quelques m\u00e9dicaments et du mat\u00e9riel m\u00e9dical dans le carrosse. Comme \u00e7a j\u2019aurais tout \u00e0 port\u00e9e de main en cas de besoin.",
    "S1S4_6": "Le couple royal doit manger, mais il peut tr\u00e8s bien choisir de loger dans un de ses palais ou dans des chambres d\u2019h\u00f4tes. Pas besoin d\u2019une cuisine \u00e0 bord.",
    "S1S4_7": "Le carrosse doit \u00eatre l\u00e9ger et efficace. Il ne s\u2019agit pas de b\u00e2tir une tour pour les si\u00e8cles \u00e0 venir mais un v\u00e9hicule. Fais-le l\u00e9ger et agile.",
    "S1S4_8": "Le temps c\u2019est de l\u2019argent mon ami.e.! Un roi et une reine n\u2019ont pas de temps \u00e0 perdre. Faite un bolide.",
    "S1S4_9": "Fais un carrosse confortable car les pav\u00e9s sont tr\u00e8s durs\u2026 sinon le roi et la reine auront bien mal aux derri\u00e8res, je peux te l'assurer!",
    "S1S4_10": "Le carrosse doit refl\u00e9ter l\u2019importance du r\u00f4le du Roi dans le monde et \u00e0 travers l\u2019Histoire du Royaume. Il doit donc \u00eatre empli de symboles historiques. Ce carrosse doit devenir l\u00e9gendaire!",
    "S1S4_11": "Hors de mon chemin, y\u2019en a qui travaillent ici !",
    "S1S4_12": "Ne laisse pas la famile royale ruiner le Royaume avec ce carrosse. Ils ont d\u00e9j\u00e0 bien plus que nous le peuple. Fais simple.",
    "S1S4_13": "Pour voyager heureux, voyagez l\u00e9ger. (Antoine de St-Exup\u00e9ry)",
    "S1S4_14": "Je n\u2019ai pas l\u2019temps de discuter. J\u2019ai du gibier \u00e0 chasser.",
    "S1S5_1": "Maintenant que tu as collect\u00e9 suffisament d\u2019avis, tu peux soit retourner \u00e0 l\u2019atelier pour commencer le projet de carrosse, soit continuer \u00e0 rencontrer d\u2019autres personnes.",
    "S2S0": "Bienvenue dans ton atelier ! Il est d\u00e9sormais temps de se lancer! En te basant sur ce que tu as entendu, tu dois concevoir le carrosse le plus adapt\u00e9 aux besoins du Roi et de la Reine.",
    "S2L1": "Lent",
    "S2L2": "Rapide",
    "S2L3": "Simple",
    "S2L4": "Sophistiqu\u00e9",
    "S2L5": "Confort de base",
    "S2L6": "Confort luxueux",
    "S2L7": "Petit",
    "S2L8": "Grand",
    "S2L9": "L\u00e9ger",
    "S2L10": "Le roi et la reine pr\u00e9f\u00e8ront-ils plut\u00f4t voyager tr\u00e8s vite ou plus lentement ?",
    "S2L11": "Le roi et la reine pr\u00e9f\u00e9reront-il plut\u00f4t un carrosse simple ou sophistiqu\u00e9?",
    "S2L12": "Le roi et la reine pr\u00e9f\u00e9reront-ils plut\u00f4t un carrosse avec un confort de base ou un carosse tr\u00e8s luxueux ?",
    "S2L13": "Le roi et la reine pr\u00e9f\u00e9reront-ils plut\u00f4t un petit carosse ou un large carrosse ?",
    "S2L14": "Le roi et la reine vont-ils pr\u00e9f\u00e9rer plut\u00f4t un carosse simple et l\u00e9ger ou un carrosse plus lourd car solide ?",
    "S2L15": "solide",
    "S2S1": "Mon ami.e, on dirait que tu n\u2019as pas pris de vraie d\u00e9cision. Un carrosse de taille moyenne ne convient pas aux besoins du Roi et de la Reine. Fais de vrais choix.",
    "S2S2": "Quel carrosse prometteur ! Beau travail !",
    "S3S1_1": "Avant de continuer avec cette id\u00e9e, peut-\u00eatre devrions nous jeter un oeil aux carrosse des autres rois et reines. Ca nous donnera surement de l\u2019inspiration.",
    "S3S1_2": "Le carrosse de la Reine Patricia est le plus rapide du royaume mais il est fragile et casse souvent.",
    "S3S1_3": "Le carrosse de la Reine Mihaela est le plus beau mais il n'est pas tr\u00e8s pratique, il est un peu lourd et c\u2019est un cauchemar quand il faut le nettoyer (la boue reste coller dans les d\u00e9cors des paroies ext\u00e9rieures).",
    "S3S1_4": "Le carrosse du Roi Pablo est le plus robuste du royaume. Il r\u00e9siste bien aux mauvaises routes et m\u00eames aux attaques ! Le Roi et la Reine ont toujours \u00e9t\u00e9 en s\u00e9curit\u00e9 dans ce carrosse! ",
    "S3S1_5": "Le carrosse de la Reine Ana est le plus confortable. M\u00eame le si\u00e8ge du cocher est doux et confortable! Dans ce carosse, tous les voyages deviennent agr\u00e9ables !",
    "S3S1_6": "Le carrosse du Roi Tharrenos est le plus grand. Il est tellement spacieux qu'on dirait qu\u2019on voyage sans m\u00eame sortir de son salon.",
    "S3S3_1": "J\u2019esp\u00e8re que ce petit tour des carrosse des autres rois et reines t\u2019as inspir\u00e9. Allez ! Remettons nous au travail !",
    "S4S1_1": "Avec toutes les informations que tu as collect\u00e9es, les diff\u00e9rentes personnes que tu as rencontr\u00e9es et les carrosse que tu as vu, et ton propre point de vue et intuition, il est d\u00e9sormais temps de faire un prototype du carrosse.",
    "S4S2_1": "Ton carrosse n\u2019est pas d'assez bonne qualit\u00e9 ! C'est un carosse royal que tu construis pas un wagon de marchant !",
    "S4S2_2": "Ton carrosse est tellement simple que \u00e7a ne prendra que quelques semaines pour le construire. Nous avons 6 mois pour le livrer, donc prenons le temps de l'am\u00e9liorer.",
    "S4S2_3": "Ton carrosse est bien trop lourd et lent. Les voyages vont prendre une \u00e9ternit\u00e9.",
    "S4S2_4": "Ton carrosse est trop brut pour un carrosse royal, on dirait une charette de paysan.",
    "S4S2_5": "Il faut que tu fasses un carrosse pas une roulotte. Fais-le plus sophistiqu\u00e9.",
    "S4S2_6": "Ton carrosse est bien trop fragile comme \u00e7a. Au moindre choc il va casser.",
    "S4S2_7": "Tu vas ruiner le Royaume ! Revoie ton design et choisis des \u00e9quipements moins chers.",
    "S4S2_8": "La famille royale a besoin du carrosse dans 6 mois. Choisis des \u00e9l\u00e9ments plus simples pour que la construction soit plus rapide.",
    "S4S3_1": "Tu dois encore am\u00e9liorer ton design avant de continuer.",
    "S4S3_2": "C'est bon ! Allons le tester !",
    "S5S0_1": "Maintenant que ton prototype est pr\u00eat, montrons le \u00e0 des gens pour voir ce qu\u2019ils en pensent avant de le pr\u00e9senter au Roi.",
    "S5S1_1": "Eh bien, \u00e7a me para\u00eet plut\u00f4t solide. On devrait faire un essai avant de le donner au Roi et \u00e0 la Reine.",
    "S5S1_2": "Bon travail mon ami. Quel beau carrosse. Mais est-ce qu\u2019il passe dans les rues \u00e9troites ? Il faudrait v\u00e9rifier \u00e7a avant de le livrer au Roi et \u00e0 la Reine.",
    "S5S1_3": "Pas mal, je dirais m\u00eame, pas mal du tout. Mais est-ce suffisament rafin\u00e9 si le couple royal devait aller \u00e0 une c\u00e9r\u00e9monie ? Tu devrais demander aux gens leur avis avant de le pr\u00e9senter au Roi et \u00e0 la Reine.",
    "S5S1_4": "\u2018D\u00e9sol\u00e9, j'ai pas le temps de papoter.",
    "S5S1_5": "J\u2019ai du travail. Demande \u00e0 quelqu\u2019un d\u2019autre.",
    "S5S1_6": "Hm ?",
    "S5S1_7": "Maintenant que tu as eu ce retour, veux-tu modifer ton design ou ignorer ce retour et garder ton design tel quel ?",
    "S5S2_1": "Maintenant tu es pr\u00eat pour un test en vrai. Par\u00e9 pour voir si ton carrosse tiens la route ? Tu vas prendre le carrosse. Arriv\u00e9.e au croisement de 3 chemins, choisis-en un.",
    "S5S2_2A": "Tu arrives avec ton carrosse dans la ville mais personne ne remarque ton arriv\u00e9e... Ca, ce n\u2019est pas bon signe. Le Carrosse Royal doit attirer l\u2019attention de tout le monde ! Des foules devraient s\u2019attrouper autour ! Tu devrais penser \u00e0 le rendre plus extraordinaire...",
    "S5S2_2": "Tu as choisis d\u2019entourer le carrosse de divertissements (musiciens, artistes), drapeaux et d\u2019animaux exotiques \u00e9l\u00e9phants\/giraffe\/chameau\/autruche, pour aller au congr\u00e8s des Rois et Reines ! Le point positif de ce choix c\u2019est qu\u2019il permet de r\u00e9pondre temporairement au besoin exceptionnel d\u2019impressionner les gens et les autres rois et reines. Bien jou\u00e9 !",
    "S5S2_3A": "Tu arrives dans la ville de ton vieil ami Lord Christophe. Quelle co\u00efncidence ! Chacun de vous pensiez vous rendre \u00e0 Portalona le lendemain. Tu devrais envisager le co-carrossage...",
    "S5S2_3": "Tu as choisis un design de carrosse pour le partage et le covoiturage. F\u00e9licitations ! La plupart des carrosse sont gar\u00e9s 80% de leur temps. Partager c\u2019est faire attention aux autres. Souviens-toi de penser \u00e0 comment r\u00e9partir le temps d\u2019utilisation du carrosse.",
    "S5S2_4A": "Tu passes le pont d\u2019Oslina... Une embuscade ! Une bande de brigands ! Mais hourra ! Tu r\u00e9ussis de justesse \u00e0 t'\u00e9chapper ! Tu devrais envisager de prot\u00e9ger d\u2019avantage le carrosse...",
    "S5S2_4": "Tu as choisi d\u2019entourer le carrosse de soldats et d\u2019armes pour faire face \u00e0 la guerre ! Ce qui est bien c\u2019est qu\u2019il n\u2019y a rien a changer au design du carrosse. Ca permet de r\u00e9pondre temporairement \u00e0 ce besoin exceptionnel avec peu d\u2019efforts. Bien jou\u00e9 !",
    "S5S2B": "De nouvelles options viennent juste d\u2019appara\u00eetre dans ton atelier. Retournes y pour les d\u00e9couvrir.",
    "S5S2C": "Maintenant que tu as am\u00e9lior\u00e9 ton carrosse, sors le pour faire un nouveau test.",
    "S6S1_1": "Le jour que nous avions tant attendu est arriv\u00e9 ! C\u2019est le moment de pr\u00e9senter le carrosse au Roi et \u00e0 la Reine.",
    "S6S1_2": "Bravo ! Vous avez fait un travail remarquable. Je suis tr\u00e8s contente.",
    "S6S1_3": "Oui, ce carrosse est parfait !",
    "S6S2_1": "Merci beaucoup. Juste une chose... vous pourriez le faire rose ?",
    "S6S2_2": "J\u2019adore, mais est-ce qu\u2019il pourrait avoir les couleurs de l\u2019arc-en-ciel ?",
    "S6S2_3": "Ce carrosse est incroyable mais pourriez-vous lui rajouter des ailes ?",
    "S6S2_4": "J\u2019aime beaucoup mais pourrait-on le recouvrir de plumes ?",
    "S6S3_1": "Mon ami vous avez fait un travail fantastique ! C\u2019est un v\u00e9ritable chef-d\u2019oeuvre ! Vous pouvez \u00eatre fi\u00e8r.e de vous. Le royaume entier vous remercie. Je ne connais pas vos plans pour l\u2019avenir, mais gardez votre esprit curieux et cr\u00e9atif !",
    "B1": "Esprit cr\u00e9atif",
    "B2": "Esprit critique",
    "B3": "Bonne \u00e9coute",
    "B4": "Pers\u00e9v\u00e9rant",
    "B5": "Solutionneur",
    "M1": "Maintenant tu peux passer \u00e0 l\u2019\u00e9tape suivante",
    "M2": "Clique sur un des personnages pour entendre son avis",
    "M3": "Clique sur un des personnages",
    "next.page": "Page suivante",
    "previous.page": "Page pr\u00e9c\u00e9dente",
    "see.result": "Voir le r\u00e9sultat",
    "next.step": "\u00c9tape suivante",
    "start": "D\u00e9marrer",
    "B6": "Fermer",
    "B7": "Indice",
    "B8": "Va \u00e0 ton atelier",
    "B9": "Tape ton pr\u00e9nom",
    "B10": "D\u00e9marrer un nouveau jeu",
    "B11": "Charger le jeu pr\u00e9c\u00e9dent",
    "S4L1": "Roues",
    "S4L2": "Ch\u00e2ssis",
    "S4L3": "Si\u00e8ge conducteur",
    "S4L4": "Si\u00e8ges int\u00e9rieurs",
    "S4L5": "Murs",
    "S4L6": "Rangement",
    "N1L1": "Construis un carrosse pour la famille royale qui soit le meilleur, le plus pratique et le plus beau",
    "N1L2": "Personnages",
    "N1L3": "Indicateurs",
    "N1L4": "Carrosses",
    "N1L5": "Exemples",
    "N1L6": "Ton carrosse",
    "N1L7": "Perturbations",
    "N1L8": "Badges",
    "N1L9": "La mission",
    "S6A1": "Merci ma reine ! J'ai beaucoup aim\u00e9 travailler sur ce projet de carrosse. D'ailleurs j'ai plusieurs id\u00e9es pour rendre le carrosse encore meilleur. Ca vous int\u00e9resse ?",
    "S6A2": "Allez-y !",
    "S6A3": "Et bien, vous pourriez rendre le carrosse",
    "S6A4": "Vous pourriez le rendre encore plus beau si vous l'entouriez de saltimbanques, musiciens et artistes, de drapeaux et d'animaux exotiques, d'\u00e9l\u00e9phants, de giraffes, de dromadaires, d'autruches. Imaginez l'impression que vous feriez au Conseil des rois et reines !",
    "S6A5": "Vous pourriez pourriez le rendre plus durable si vous l'am\u00e9nagez pour le partage. La plupart des carrosses sont gar\u00e9s 80% du temps ! Partagez votre carrosse ! ",
    "S6A6": "Et des suggestions pour moi ?",
    "S6A7": "Vous pourriez prot\u00e9ger votre carrosse en l'\u00e9quippant pour la guerre. Des parois plus \u00e9paisses ne suffiront pas, entourez votre carrosse de soldats, de boucliers et de piques. Ceux qui veulent vous attaquer y r\u00e9fl\u00e9chiront \u00e0 deux fois!",
    "ending": "Fin",
}