export const data = {
"S1S1_1": "Hei min venn! ",
"S1S1_2": "Hei!",
"S1S1_3": "Jeg er Kongens budbringer. Vi har et oppdrag til deg. Kongen har h\u00f8rt at du er den beste h\u00e5ndverkeren i riket, og at du finner gode l\u00f8sninger p\u00e5 alle problemer. Er dette sant?",
"S1S1_4": "Vel, jeg gj\u00f8r mitt beste.",
"S1S1_5": "Ikke v\u00e6r s\u00e5 ydmyk. Hvis dette stemmer, ta med tingene dine og bli med meg til Lalandias hovedstad - Empatheia!",
"S1S2_1": "\u00c5h! Jeg er glad du aksepterte invitasjonen min. Jeg er kongen av Lalandia, og trenger en ny vogn for \u00e5 reise gjennom riket. Ryktene sier at du er den beste h\u00e5ndverkeren i hele riket. Mitt oppdrag for deg, dersom du aksepterer, er \u00e5 bygge verdens beste vogn til meg.",
"S1S2_2": "Jeg er dronningen av Lalandia. Jeg vil ogs\u00e5 bruke denne vognen for \u00e5 reise rundt i riket. Jeg trenger b\u00e5de en praktisk vogn, men den m\u00e5 selvf\u00f8lgelig v\u00e6re den vakreste i verden.",
"S1S2_3": "Ja, ja, Den trenger alt dette, og den m\u00e5 v\u00e6re ferdig om 6 m\u00e5neder. Vi skal dra til De Store Kongers R\u00e5d hvor alle kongene i Nord m\u00f8tes. Si meg, aksepterer du oppdraget?",
"S1S2_4": "Deres majestet, det vil v\u00e6re en \u00e6re \u00e5 akseptere dette utfordrende oppdraget. For \u00e5 kunne lage denne vognen vil jeg m\u00e5tte stille dere mange sp\u00f8rsm\u00e5l for \u00e5 forst\u00e5 hva dere trenger.",
"S1S2_5": "Gutten min, du vet alt du trenger. Vi har akkurat sagt hva vi er ute etter. N\u00e5, kom deg avg\u00e5rde! Dronningen og jeg f\u00e5r bes\u00f8k av S\u00f8rhavsprinsen, og har ikke mer tid til \u00e5 diskutere saken. Lykke til!",
"S1S2_6": "Men hva slags vogn skal jeg tegne? Hva skal de ulike funksjonene v\u00e6re? Jeg vet ikke hva kongen og dronningen virkelig trenger. Jeg vet ikke hvor jeg skal starte.",
"S1S3_1": "Hva er den beste, mest praktiske, og vakreste vognen i verden? Du vil n\u00e5 f\u00e5 m\u00f8te mange karakterer som vil fortelle deg hva de mener om saken. ",
"S1S3_2": "Har du g\u00e5tt deg bort?",
"S1S3_3": "Ja, litt. Kongen og dronningen ga meg nettopp oppdraget \u00e5 lage de en ny vogn. Men jeg trenger mer informasjon s\u00e5 jeg kan gj\u00f8re en god jobb. Hva trenger de den til? Hva skal den gj\u00f8re? Hvilke veityper skal den reise p\u00e5? Hvor stor burde den v\u00e6re? Hva slags funksjoner tregner den? De var ganske utydelige n\u00e5r de bestilte.",
"S1S3_4": "Min venn, du m\u00e5 bygge en sterk og robust vogn. Den m\u00e5 v\u00e6re trygg nok til at kongefamilien kan reise i den. Den trenger ikke v\u00e6re vakker, fordi en sterk vogn er er vakker vogn. Kanskje du burde snakke med andre og h\u00f8re hva de tenker.",
"S1S4_1": "Lange reiser kan v\u00e6re slitsomme. Vognen m\u00e5 v\u00e6re komfortabel. Ikke bare for min del, men for kongeparet!",
"S1S4_2": "Vognen burde v\u00e6re den dyreste som noensinne har blitt laget i kongeriket. Den m\u00e5 vise Kongens makt og rikdom, og burde v\u00e6re et luksuri\u00f8st kunststykke.",
"S1S4_3": "Kongefamilien har mange ting de m\u00e5 frakte med seg. Kl\u00e6r, gaver, og s\u00e5 videre. De trenger plass til \u00e5 ha med seg alt.",
"S1S4_4": "Tenk p\u00e5 hestene som vil trekke vognen. Hvis du \u00f8nsker \u00e5 kj\u00f8re fort m\u00e5 vognen v\u00e6re liten og lett. Ellers blir hesten utslitt veldig fort.",
"S1S4_5": "Det hadde v\u00e6rt flott om vognen kunne hatt plass til mitt medisinske utstyr og medikamenter. Jeg kunne hatt med meg alt jeg trenger.",
"S1S4_6": "Kongeparet m\u00e5 jo spise, men kan bo i andre slott eller gjestehus. Det er ikke behov for et lite kj\u00f8kken ombord.",
"S1S4_7": "Vognen m\u00e5 v\u00e6re lett og effektiv. Du bygger ikke et t\u00e5rn som skal t\u00e5le tidens tann, men en reisevogn. Den b\u00f8r v\u00e6re lett og smidig.",
"S1S4_8": "Tid er penger min venn. Kongen og dronningen har ikke tid til overs. Bare lag den s\u00e5 rask som mulig.",
"S1S4_9": "Lag vognen komfortabel fordi brosteinene er veldig harde. Kongen og dronningen vil f\u00e5 vondt i rompa... Det kan jeg love deg.",
"S1S4_10": "Vognen m\u00e5 reflektere viktigheten av kongens rolle i verden og rikets historie. Derfor m\u00e5 den inneholde mange historiske symboler. Vognen burde bli et legendarisk artefakt.",
"S1S4_11": "Kom deg unna gutt! Folk jobber her!",
"S1S4_12": "Ikke la kongefamilien ruinere konged\u00f8mmet med denne vognen. De har allerede s\u00e5 mye mer enn vi - folket - har. Gj\u00f8r vognen s\u00e5 enkel som mulig.",
"S1S4_13": "\"Han som reiser lykkelig m\u00e5 reise lett\" (Antoine de St Exupery)",
"S1S4_14": "Jeg har ikke tid til \u00e5 diskutere dette. Jeg ordner noe kj\u00f8tt.",
"S1S5_1": "N\u00e5 som du har samlet nok synspunkter kan du g\u00e5 tilbake til verkstedet og begynne \u00e5 jobbe p\u00e5 vognen, eller fortsette \u00e5 m\u00f8te andre mennesker.",
"S2S0": "Velkommen tilbake til verkstedet! Basert p\u00e5 hva du har h\u00f8rt er det p\u00e5 tide \u00e5 ta noen valg om hva slags vogn du tror best passer Kongen og Dronningens behov.",
"S2L1": "Sakte",
"S2L2": "Raskt",
"S2L3": "R\u00f8ft",
"S2L4": "Stilig",
"S2L5": "Basis komfort",
"S2L6": "Luksus komfort",
"S2L7": "Liten",
"S2L8": "Stor",
"S2L9": "Lett",
"S2L10": "Vil kongen og dronningen foretrekke h\u00f8y hastighet eller \u00e5 reise langsommere, men sikkert p\u00e5 alle typer veier?",
"S2L11": "Vil kongen og dronningen foretrekke en holdbar vogn eller et ganske stilig kj\u00f8ret\u00f8y?",
"S2L12": "Vil kongen og dronningen foretrekke en minimalistisk, men praktisk vogn eller en som er veldig luksuri\u00f8s?",
"S2L13": "Vil kongen og dronningen foretrekke en liten rask vogn eller en romslig, men saktere vogn?",
"S2L14": "Vil kongen og dronningen foretrekke en lett, enkel vogn eller en sv\u00e6rt robust og tung vogn?",
"S2L15": "Sterk",
"S2S1": "Min venn, det ser ut som at du ikke har tatt en beslutning. En middelm\u00e5dig vogn vil ikke dekke Kongen og Dronningens behov. Ta noen valg!",
"S2S2": "Denne vognen ser lovende ut. Bra jobbet!",
"S3S1_1": "F\u00f8r vi g\u00e5r videre med planen v\u00e5r burde vi sjekke hvilke vogner andre konger og dronninger har. Det kan gi oss inspirasjon.",
"S3S1_2": "Vognen til Dronning Patricia er den raskteste i kongeriket, men g\u00e5r ofte i stykker.",
"S3S1_3": "Vognen til Dronning Mihaela er den vakreste, men er ikke veldig praktisk. Den er litt for tung, og et mareritt \u00e5 vaske. All pynten blir fort skitten.",
"S3S1_4": "Vognen til Kong Pablo er den sterkeste i kongeriket. Den har overlevet alle d\u00e5rlige veier og mange angrep, og har alltid lykkes \u00e5 holde Kongen og Dronningen trygg.",
"S3S1_5": "Vognen til Dronning Ana er den mest komfortable. Selv setet til kusken er laget av mykt materiale. Det gj\u00f8r hver reise hyggelig.",
"S3S1_6": "Vognen til Kong Tharrenos er den st\u00f8rste, og har masse plass. \u00c5 reise med den f\u00f8les \u00e5 reise uten \u00e5 g\u00e5 ut av sin egen stue.",
"S3S3_1": "Jeg h\u00e5per visningen av vognene til andre konger og dronninger har inspirert deg. N\u00e5, la oss fortsette med v\u00e5rt!",
"S4S1_1": "Med all informasjonen du har f\u00e5tt fra folk du har m\u00f8tt, vognene du har sett, og dine egne synspnkter, er det n\u00e5 p\u00e5 tide \u00e5 starte \u00e5 lage en prototype av vognen.",
"S4S2_1": "Vognen din er for billig. Du bygger vogn til kongefamilien! Ikke en vanlig vogn!",
"S4S2_2": "Vognen din er s\u00e5 enkel at det tar bare noen uker \u00e5 bygge den. Vi kan bruke mer tid fordi vi har 6 m\u00e5neder \u00e5 levere den p\u00e5. La oss forbedre vognen.",
"S4S2_3": "Vognen din er for tung og g\u00e5r for sakte. Reiser vil ta evigheter.",
"S4S2_4": "Vognen din er for robust. Den ser ut som en arbeidsvogn.",
"S4S2_5": "Du m\u00e5 bygge en vogn, ikke en luksus villa. Gj\u00f8r det enklere!",
"S4S2_6": "Vognen din er for skj\u00f8r. Den vil falle sammen p\u00e5 f\u00f8rste brostein.",
"S4S2_7": "Du ruinerer kongeriket! Tenk deg om og velg mindre dyre elementer.",
"S4S2_8": "Kongefamilien trenger at vognen er klar om 6 m\u00e5neder. Velg noen enklere elementer for at det tar mindre tid \u00e5 bygge den.",
"S4S3_1": "Du trenger \u00e5 forbedre designet f\u00f8r du fortsetter.",
"S4S3_2": "Ok! La oss fortsette testingen!",
"S5S0_1": "N\u00e5 som prototypen, eller f\u00f8rste fors\u00f8ket ditt er klar,  er det p\u00e5 tide \u00e5 vise den til andre og h\u00f8re hva de synes f\u00f8r du presenterer den til Kongen.",
"S5S1_1": "Vel, den virker ganske kraftig. Vi burde pr\u00f8ve \u00e5 gi den til Kongen og Dronningen.",
"S5S1_2": "Bra jobbet min venn! Det er en veldig fin vogn! Men, tror du den f\u00e5r plass i de trange gatene? Du m\u00e5 pr\u00f8ve det f\u00f8r du leverer den.",
"S5S1_3": "Ikke s\u00e5 verst! Men, tror du den er fin nok til at kongeparet kan bruke den til en seremoni? Du burde sp\u00f8rre hva andre folk synes f\u00f8r du leverer den til Kongen og Dronningen.",
"S5S1_4": "Beklager, jeg har ikke tid!",
"S5S1_5": "Jeg m\u00e5 jobbe. Sp\u00f8r noen andre!",
"S5S1_6": "H\u00e6?",
"S5S1_7": "Basert p\u00e5 tilbakemeldingen du nettopp fikk, \u00f8nsker \u00e5 gj\u00f8re om p\u00e5 noe, eller fortsette slik det er n\u00e5?",
"S5S2_1": "Du er n\u00e5 klar for den f\u00f8rste pr\u00f8ven. Er du klar til \u00e5 se om vognen er bra nok? Du skal kj\u00f8re vognen til et veikryss. Her kan du velge mellom 3 veier. Velg en av de 3 veiene.",
"S5S2_2": "Du har valgt \u00e5 omringe vognen din med underholdere (musikere, kunstnere), flagg og spennende dyr som elefanter, giraffer, kameler og strutser. N\u00e5, g\u00e5 til kongressen for Konger og Droninger. Det som er bra er at dette ikke p\u00e5virker vognen, men lar kongeparet vise seg. Bra gjort!  ",
"S5S2_3": "Du har n\u00e5 valgt \u00e5 designe vognen for \u00e5 deles. Gratulerer! De fleste vogner st\u00e5r parkert 80% av tiden, s\u00e5 det er fint \u00e5 dele. Husk at \u00e5 tenke p\u00e5 hvordan man skal dele tiden vognen blir brukt.",
"S5S2_4": "Du har valgt \u00e5 omringe vognen med soldater og v\u00e5pen for \u00e5 g\u00e5 i krigen. Det er bra at du ikke m\u00e5 endre designet. Bra jobbet!",
"S6S1_1": "Dette er dagen vi har ventet p\u00e5. Det er p\u00e5 tide \u00e5 presentere vognen til Kongen og dronningen.",
"S6S1_2": "Bra jobbet! Du har gjort en fantastisk jobb. Jeg er veldig forn\u00f8yd med den.",
"S6S1_3": "Ja! Den vognen er perfekt.",
"S6S2_1": "Tusen takk, kan du lage den i rosa?",
"S6S2_2": "Jeg elsker den, kan du lage den i regnbuens farger?",
"S6S2_3": "Det er en fantastisk vogn, kan du lage den med vinger?",
"S6S2_4": "Jeg liker den veldig godt, kan du dekke den med fj\u00e6r?",
"S6S3_1": "Min venn, du har gjort et utrolig stykke arbeid. Dette er et mesterverk! Du kan all grunn til \u00e5 v\u00e6re stolt. Hele kongeriket er takknemlig. Jeg vet ikke hva slags planer du har for fremtiden, men ikke mist kreativiteten din.",
"B1": "Kreativt sinn",
"B2": "Kritisk tenker",
"B3": "Lytter",
"B4": "En som aldri gir opp",
"B5": "Probleml\u00f8ser",
"M1": "N\u00e5 kan du g\u00e5 videre til neste trinn",
"M2": "Klikk p\u00e5 en person for \u00e5 motta tilbakemelding",
"M3": "Klikk p\u00e5 en person",
"next.page": "Neste side ",
"previous.page": "Forrige side ",
"see.result": "Se resultatene",
"next.step": "Neste steg ",
"start": "start ",
"B6": "lukk ",
"B7": "hint",
"B8": "g\u00e5 til verksted",
"B9": "sett inn navnet ditt",
"B10": "start et nytt spil",
"B11": "last forrige spill",
"S4L1": "hjul",
"S4L2": "chassis ",
"S4L3": "sj\u00e5f\u00f8rsete",
"S4L4": "seter inne",
"S4L5": "vegger ",
"S4L6": "oppbevaring",
"N1L1": "Bygg den beste, praktiske og most koselige vognen til den kongelige familien",
"N1L2": "karakterer",
"N1L3": "indikatorer ",
"N1L4": "vogner ",
"N1L5": "eksempler ",
"N1L6": "din vogn ",
"N1L7": "forstyrrelser",
"N1L8": "merker",
"N1L9": "Oppdraget",
"S6A1": "Takk, deres kongelige h\u00f8yhet! Jeg trivdes virkelig med \u00e5 jobbe med dette! Jeg hadde mange andre ideer mens jeg pr\u00f8vde \u00e5 designe den beste vognen, kanskje noen ville v\u00e6re nyttige for deg?",
"S6A2": "V\u00e6rs\u00e5god!",
"S6A3": "Vel, kanskje du kan gj\u00f8re vognen mer ...",
"S6A4": "enda vakrere ved \u00e5 omgi vognen med entertainere (musikere, kunstnere, soldater), flagg og stilige dyr elefanter \/ giraffer \/ kamel \/ struts, \u00e5 g\u00e5 til kongressen av konger og dronninger! Jeg vedder p\u00e5 at alle vil bli veldig imponert.",
"S6A5": "Milj\u00f8vennlig og design vognen for deling ved \u00e5 gj\u00f8re den st\u00f8rre! De fleste vogner st\u00e5r parkert 80% av tiden. \u00c5 dele er \u00e5 bry seg",
"S6A6": "Har du noe forslag til meg? ",
"S6A7": "Ja, deres majestet. Kanskje du kan gj\u00f8re din vogn robust, tilpasset krigens krav. Tykkere vegger vil ikke v\u00e6re nok, du m\u00e5 omgi vognen med soldater og skjold \/ spyd festet til veggene. Det vil sikkert imponere eventuelle angripere.",

"ending": "End",
}