export const data = {
    "S1S1_1": "Olá!",
    "S1S1_2": "Olá!",
    "S1S1_3": "Sou o mensageiro do Rei. Temos uma missão para ti. Chegou aos ouvidos do Rei que o teu trabalho de artesanato é o melhor no reino e encontras sempre as melhores soluções para todos os problemas. É verdade?",
    "S1S1_4": "Bem, tento sempre fazer o meu melhor.",
    "S1S1_5": "Não sejas tão humilde. Se isso é verdade, tens de me acompanhar até à Empateia, a cidade real de Lalandia.",
    "S1S2_1": "Ah! Fico contente por aceitares o meu convite. Sou o Rei de Lalandia. Preciso de uma nova carruagem para viajar pelo reino. E disserem-me que o teu trabalho de artesanato é o melhor do reino. Se aceitares, a missão que tenho para ti implica construires a melhor carruagem do mundo.",
    "S1S2_2": "Olá, eu sou a Rainha de Lalandia. Também preciso desta nova carruagem para passear pelo reino. Necessito que seja prática, mas também a mais bonita do mundo.",
    "S1S2_3": "Sim, sim. Precisa de ter tudo isso. E precisamos que esteja pronta em 6 meses porque iremos à Reunião Geral dos Reis, onde todos os Reis do Norte se encontram. Aceitas esta missão?",
    "S1S2_4": "Minha Rainha, meu Rei, será uma honra aceitar esta missão tão desafiante. Eu aceito a missão. Mas para conseguir construir esta carruagem tenho muitas questões a fazer, para perceber o que pretendem.",
    "S1S2_5": "Bem, penso que já te dissemos tudo o que precisas saber. Agora vai! Não temos mais tempo para falar sobre isto, porque vamos receber agora o Príncipe do Mar do Sul. Boa sorte!",
    "S1S2_6": "Mas que tipo de carruagem devo construir? Quais as principais funções? Não tenho ideia do que o Rei e a Rainha realmente precisam. Isto ainda é muito confuso.",
    "S1S3_1": "Como será a carruagem mais prática, a melhor e a mais bonita do mundo? Vais entrar num mundo de habitantes do reino que partilham diferentes opiniões sobre como deve ser esta carruagem.",
    "S1S3_2": "Está tudo bem?",
    "S1S3_3": "Bem, acho a minha missão pouco clara. O Rei e a Rainha pediram-me para construir uma nova carruagem para eles. Mas preciso de mais informação para poder fazer um bom projeto. Para que precisam dela? O que deverá fazer? Em que tipo de estradas viajam normalmente? Qual o tamanho que deve ter? Quais devem ser as suas funções? Eles não falaram muito sobre o que esperam da carruagem.",
    "S1S3_4": "Tens de construir uma carruagem forte e resistente! Deve ser segura para a família real viajar. E não são necessários luxos, também existe beleza na robustez. Mas talvez seja melhor procurares outras opiniões pelo reino.",
    "S1S4_1": "As viagens longas podem ser muito cansativas. A carruagem deve ser confortável. E não digo isto apenas para mim, mas também para a família real.",
    "S1S4_2": "A carruagem deve ser a mais rica alguma vez construída no reino para mostrar o poder do Rei e a riqueza do nosso reino, deve ser uma obra de arte e de luxo.",
    "S1S4_3": "A família real tem sempre muitas coisas para transportar: roupa, presentes, etc. Por isso, preciso de espaço para colocar tudo na carruagem.",
    "S1S4_4": "Pensa nos cavalos que vão puxar a carruagem. Se pretendes que seja rápida, a carruagem deve ser leve e pequena. Caso contrário, os cavalos cansam-se rapidamente.",
    "S1S4_5": "Seria óptimo se desse para incluir na carruagem alguns dos meus instrumentos médicos e medicamentos. Assim teria tudo à disposição, caso seja necessário.",
    "S1S4_6": "A família real tem de comer, mas pode fazê-lo num dos seus palácios ou em outros palacetes quando são convidados. Não é necessário ter uma mini-cozinha a bordo.",
    "S1S4_7": "A carruagem deve ser leve e eficiente. Não vais construir uma torre para durar séculos, mas umveículo para viagens. Faz com que sejaleve e ágil.",
    "S1S4_8": "Tempo é dinheiro! O Rei e a Rainha não têm tempo a perder em viagens. Faz com que seja uma carruagem rápida.",
    "S1S4_9": "Constrói uma carruagem confortável porque o piso da estrada é muito irregular… e o Rei e a Rainha vão saltar durante toda a viagem e podem magoar-se… Posso garantir isso!",
    "S1S4_10": "A carruagem deve refletir a importância do papel do Rei e da Rainha no mundo, assim como a história do reino e, por isso, deve contemplar símbolos históricos, transformando esta carruagem num artefacto lendário.",
    "S1S4_11": "Sai do meu caminho! Aqui as pessoas trabalham!",
    "S1S4_12": "Não permitas que a família real arruine o reino com esta carruagem. Eles já têm muito mais que nós. Faz com que seja simples.",
    "S1S4_13": "Aquele que quer viajar feliz, deve viajar leve. (Antoine de St Exupery)",
    "S1S4_14": "Eu não tenho tempo para discutir. Tenho carne para caçar.",
    "S1S5_1": "Agora que reuniste várias opiniões, podes regressar à tua oficina e começar a trabalhar no projeto da carruagem ou podes optar por continuar a falar com outras pessoas.",
    "S2S0": "Estás de regresso à tua oficina! Com base no que ouviste, chegou o momento de tomar decisões sobre o tipo de carruagem que achas que melhor satisfaz as necessiades do Rei e da Rainha.",
    "S2S1": "Hum… parece que não fizeste a melhor opção. Uma carruagem básica não satisfará as necessidades do Rei e da Rainha. Repensa as tuas decisões.",
    "S2S2": "Que carruagem tão promissora! Muito bem!",
    "S3S1_1": "Antes de continuarmos com este projeto, podemos observar carruagens de outros Reis e Rainhas. Talvez isso te inspire.",
    "S3S1_2": "A carruagem da Rainha Patrícia é a mais rápida do reino, mas por vezes os travões falham.",
    "S3S1_3": "A carruagem da Rainha Mihaela é a mais bonita mas não é muito conveniente. É ligeiramente pesada e um pesadelo para limpar - a lama fica agarrada a todos os elementos decorativos das paredes exteriores.",
    "S3S1_4": "A carruagem do Rei Pablo é a mais forte de todo o reino. Já sobreviveu a péssimas estradas e até a vários ataques; é um êxito a manter o Rei e a Rainha em segurança.",
    "S3S1_5": "A carruagem da rainha Ana é a mais confortável. Até o assento do cocheiro é feito de materiais muito suaves e confortáveis. Viajar nesta carruagem é um prazer.",
    "S3S1_6": "A carruagem do Rei Tharrenos é a maior. Oferece muito espaço. Viajar nesta carruagem é como estar na nossa sala de estar.",
    "S3S3_1": "Espero que esta visita a carruagens de outros reis e rainhas te tenha inspirado. Agora vamos continuar com o teu projeto!",
    "S4S1_1": "Com a informação que reuniste de todas as pessoas com quem falaste, da exploração de outras carruagens e com a tua opinião e intuição, chegou o momento de avançar para a prototipagem da carruagem.",
    "S4S2_1": "A tua carruagem está muito pobre. Estás a construir a carruagem da família real! E não o carrinho de um comerciante!",
    "S4S2_2": "A tua carruagem é tão simples que só demorarás 2 semanas a construi-la. Podes investir mais tempo, pois tens 6 meses para a entregar. Vamos melhorar a carruagem!",
    "S4S2_3": "A carruagem é demasiado pesada e lenta. As viagens vão demorar uma eternidade!",
    "S4S2_4": "A carruagem é demasiado grosseiropara uma carruagem real,mais parece uma carruagem de camponeses.",
    "S4S2_5": "Tens fazer uma carruagem e não uma charrete. Faz com que seja mais adequada!",
    "S4S2_6": "Da forma como está construída, esta carruagem é muito frágil. Vai desmontar-se assim que embater numa pedra da calçada.",
    "S4S2_7": "Vais arruinar o reino! Reconsidera as opções que fizeste para a carruagem e escolhe elementos mais baratos.",
    "S4S2_8": "A família real precisa da carruagem pronta em 6 meses. Escolhe alguns elementos mais simples para reduzir o tempo de construção.",
    "S4S3_1": "Precisas de melhorar o teu projetoantes de continuar.",
    "S4S3_2": "Ok! Vamos testar a carruagem!",
    "S5S0_1": "Agora que o protótipo da carruagem está pronto, vamos apresentar a algumas pessoas e receber o seu feedback antes de apresentar a carruagem ao Rei.",
    "S5S1_1": "Bem, parece-me bastante forte. Devemos experimentá-la antes de a entregar ao Rei e à Rainha.",
    "S5S1_2": "Muito bem! É uma boa carruagem. Mas achas que passa por ruas estreitas? Talvez seja melhor testá-la antes de a entregar.",
    "S5S1_3": "Nada mal. Nada mal, mesmo! Mas achas que é elegante o suficiente para a família real ir a uma cerimómia? Devias perguntar às pessoas o que acham da carruagem antes de a entregar ao Rei e à Rainha.",
    "S5S1_4": "Desculpa, mas não tenho tempo para conversar.",
    "S5S1_5": "Tenho muito para fazer... Pergunta a outra pessoa.",
    "S5S1_6": "Desculpa?",
    "S5S1_7": "Com base no feedback que recebeste, queres rever o teu projeto ou vais ignorar as sugestões e manter a carruagem como está agora?",
    "S5S2_1": "Tens tudo pronto para testar a carruagem lá fora! Vamos ver se a tua carruagem funciona? Agora, vais sair com a tua carruagem mas terás de parar num cruzamento com três caminhos. Escolhe um dos três caminhos para continuares.",
    "S5S2_2": "Escolheste acompanhar a tua carruagem com artistas, bandeiras e animais majestosos, para ir ao Conselho de reis e rainhas! Esta opção não altera o projeto inicial da tua carruagem e permite responder à necessidade temporária de chamar a atenção para o Rei e a Rainha. Muito bem!",
    "S5S2_3": "Escolheste redesenhar a tua carruagem para a partilhar! Parabéns! A maioria das carruagens estão inutilizadas 80% do tempo, mas agora pode ser partilhada. Considera também a necessidade em partilhar o tempo em que a carruagem pode ser utilizada.",
    "S5S2_4": "Escolheste acompanhar a carruagem com soldados e armas para defender a família real! Assim, não precisas de alterar o projeto inicial da carruagem e respondes a uma necessidade excecional de reforçar a defesa sem grandes custos. Muito bem!",
    "S6S1_1": "Chegou o dia que tanto esperávamos! Este é o momento para apresnetar a carruagem ao Rei e à Rainha.",
    "S6S1_2": "Muito bem! Fizeste um trabalho fantástico. Estou muito satisfeita com a carruagem.",
    "S6S1_3": "Sim! A carruagem é perfeita!",
    "S6S2_1": "Muito obrigado, mas podes pintá-la com cor de rosa?",
    "S6S2_2": "Adorei, mas podes pintá-la como um arco-íris?",
    "S6S2_3": "É uma carruagem espetacular, mas podes colocar-lhe asas?",
    "S6S2_4": "Gosto muito, mas é possível cobri-la com penas?",
    "S6S3_1": "Fizeste um trabalho incrível! Isto é uma obra de arte! Podes sentir muito orgulho pelo teu trabalho. Todo o reino te agradece! Não sei quais são os teus planos para o futuro, mas tens de aproveitar a tua criatividade!",
    "next.page": "",
    "previous.page": "",
    "see.result": "",
    "next.step": "",
    "start": "",    
}