export const data = {
    "S1S1_1": "Ol\u00e1!",
    "S1S1_2": "Ol\u00e1!",
    "S1S1_3": "Sou o mensageiro do Rei. Temos uma miss\u00e3o para ti. Chegou aos ouvidos do Rei que o teu trabalho de artesanato \u00e9 o melhor no reino e encontras sempre as melhores solu\u00e7\u00f5es para todos os problemas. \u00c9 verdade?",
    "S1S1_4": "Bem, tento sempre fazer o meu melhor.",
    "S1S1_5": "N\u00e3o sejas t\u00e3o humilde. Se isso \u00e9 verdade, tens de me acompanhar at\u00e9 \u00e0 Empateia, a cidade real de Lalandia.",
    "S1S2_1": "Ah! Fico contente por aceitares o meu convite. Sou o Rei de Lalandia. Preciso de uma nova carruagem para viajar pelo reino. E disserem-me que o teu trabalho de artesanato \u00e9 o melhor do reino. Se aceitares, a miss\u00e3o que tenho para ti implica construires a melhor carruagem do mundo.",
    "S1S2_2": "Ol\u00e1, eu sou a Rainha de Lalandia. Tamb\u00e9m preciso desta nova carruagem para passear pelo reino. Necessito que seja pr\u00e1tica, mas tamb\u00e9m a mais bonita do mundo.",
    "S1S2_3": "Sim, sim. Precisa de ter tudo isso. E precisamos que esteja pronta em 6 meses porque iremos \u00e0 Reuni\u00e3o Geral dos Reis, onde todos os Reis do Norte se encontram. Aceitas esta miss\u00e3o?",
    "S1S2_4": "Minha Rainha, meu Rei, ser\u00e1 uma honra aceitar esta miss\u00e3o t\u00e3o desafiante. Eu aceito a miss\u00e3o. Mas para conseguir construir esta carruagem tenho muitas quest\u00f5es a fazer, para perceber o que pretendem.",
    "S1S2_5": "Bem, penso que j\u00e1 te dissemos tudo o que precisas saber. Agora vai! N\u00e3o temos mais tempo para falar sobre isto, porque vamos receber agora o Pr\u00edncipe do Mar do Sul. Boa sorte!",
    "S1S2_6": "Mas que tipo de carruagem devo construir? Quais as principais fun\u00e7\u00f5es? N\u00e3o tenho ideia do que o Rei e a Rainha realmente precisam. Isto ainda \u00e9 muito confuso.",
    "S1S3_1": "Como ser\u00e1 a carruagem mais pr\u00e1tica, a melhor e a mais bonita do mundo? Vais entrar num mundo de habitantes do reino que partilham diferentes opini\u00f5es sobre como deve ser esta carruagem.",
    "S1S3_2": "Est\u00e1 tudo bem?",
    "S1S3_3": "Bem, acho a minha miss\u00e3o pouco clara. O Rei e a Rainha pediram-me para construir uma nova carruagem para eles. Mas preciso de mais informa\u00e7\u00e3o para poder fazer um bom projeto. Para que precisam dela? O que dever\u00e1 fazer? Em que tipo de estradas viajam normalmente? Qual o tamanho que deve ter? Quais devem ser as suas fun\u00e7\u00f5es? Eles n\u00e3o falaram muito sobre o que esperam da carruagem.",
    "S1S3_4": "Tens de construir uma carruagem forte e resistente! Deve ser segura para a fam\u00edlia real viajar. E n\u00e3o s\u00e3o necess\u00e1rios luxos, tamb\u00e9m existe beleza na robustez. Mas talvez seja melhor procurares outras opini\u00f5es pelo reino.",
    "S1S4_1": "As viagens longas podem ser muito cansativas. A carruagem deve ser confort\u00e1vel. E n\u00e3o digo isto apenas para mim, mas tamb\u00e9m para a fam\u00edlia real.",
    "S1S4_2": "A carruagem deve ser a mais rica alguma vez constru\u00edda no reino para mostrar o poder do Rei e a riqueza do nosso reino, deve ser uma obra de arte e de luxo.",
    "S1S4_3": "A fam\u00edlia real tem sempre muitas coisas para transportar: roupa, presentes, etc. Por isso, preciso de espa\u00e7o para colocar tudo na carruagem.",
    "S1S4_4": "Pensa nos cavalos que v\u00e3o puxar a carruagem. Se pretendes que seja r\u00e1pida, a carruagem deve ser leve e pequena. Caso contr\u00e1rio, os cavalos cansam-se rapidamente.",
    "S1S4_5": "Seria \u00f3ptimo se desse para incluir na carruagem alguns dos meus instrumentos m\u00e9dicos e medicamentos. Assim teria tudo \u00e0 disposi\u00e7\u00e3o, caso seja necess\u00e1rio.",
    "S1S4_6": "A fam\u00edlia real tem de comer, mas pode faz\u00ea-lo num dos seus pal\u00e1cios ou em outros palacetes quando s\u00e3o convidados. N\u00e3o \u00e9 necess\u00e1rio ter uma mini-cozinha a bordo.",
    "S1S4_7": "A carruagem deve ser leve e eficiente. N\u00e3o vais construir uma torre para durar s\u00e9culos, mas umve\u00edculo para viagens. Faz com que sejaleve e \u00e1gil.",
    "S1S4_8": "Tempo \u00e9 dinheiro! O Rei e a Rainha n\u00e3o t\u00eam tempo a perder em viagens. Faz com que seja uma carruagem r\u00e1pida.",
    "S1S4_9": "Constr\u00f3i uma carruagem confort\u00e1vel porque o piso da estrada \u00e9 muito irregular... e o Rei e a Rainha v\u00e3o saltar durante toda a viagem e podem magoar-se... Posso garantir isso!",
    "S1S4_10": "A carruagem deve refletir a import\u00e2ncia do papel do Rei e da Rainha no mundo, assim como a hist\u00f3ria do reino e, por isso, deve contemplar s\u00edmbolos hist\u00f3ricos, transformando esta carruagem num artefacto lend\u00e1rio.",
    "S1S4_11": "Sai do meu caminho! Aqui as pessoas trabalham!",
    "S1S4_12": "N\u00e3o permitas que a fam\u00edlia real arruine o reino com esta carruagem. Eles j\u00e1 t\u00eam muito mais que n\u00f3s. Faz com que seja simples.",
    "S1S4_13": "Aquele que quer viajar feliz, deve viajar leve. (Antoine de St Exupery)",
    "S1S4_14": "Eu n\u00e3o tenho tempo para discutir. Tenho carne para ca\u00e7ar.",
    "S1S5_1": "Agora que reuniste v\u00e1rias opini\u00f5es, podes regressar \u00e0 tua oficina e come\u00e7ar a trabalhar no projeto da carruagem ou podes optar por continuar a falar com outras pessoas.",
    "S2S0": "Est\u00e1s de regresso \u00e0 tua oficina! Com base no que ouviste, chegou o momento de tomar decis\u00f5es sobre o tipo de carruagem que achas que melhor satisfaz as necessiades do Rei e da Rainha.",
    "S2L1": "Lenta",
    "S2L2": "R\u00e1pida",
    "S2L3": "R\u00fastica",
    "S2L4": "Sofisticada",
    "S2L5": "M\u00ednimo conforto",
    "S2L6": "Conforto de luxo",
    "S2L7": "Pequena",
    "S2L8": "Larga",
    "S2L9": "Leve",
    "S2L10": "Ser\u00e1 que o Rei e a Rainha preferem viajar numa carruagem r\u00e1pida ou numa mais lenta e mais segura?",
    "S2L11": "Ser\u00e1 que o Rei e a Rainha preferem viajar numa carruagem resistente ou numa mais vistosa?",
    "S2L12": "Ser\u00e1 que o Rei e a Rainha preferem viajar numa carruagem pr\u00e1tica e minimalista ou numa mais luxuosa?",
    "S2L13": "Ser\u00e1 que o Rei e a Rainha preferem viajar numa carruagem pequena e r\u00e1pida ou numa mais c\u00f3moda e lenta?",
    "S2L14": "Ser\u00e1 que o Rei e a Rainha preferem viajar numa carruagem b\u00e1sica e leve ou numa mais robusta e pesada?",
    "S2L15": "Robusta",
    "S2S1": "Hum... parece que n\u00e3o fizeste a melhor op\u00e7\u00e3o. Uma carruagem b\u00e1sica n\u00e3o satisfar\u00e1 as necessidades do Rei e da Rainha. Repensa as tuas decis\u00f5es.",
    "S2S2": "Que carruagem t\u00e3o promissora! Muito bem!",
    "S3S1_1": "Antes de continuarmos com este projeto, podemos observar carruagens de outros Reis e Rainhas. Talvez isso te inspire.",
    "S3S1_2": "A carruagem da Rainha Patr\u00edcia \u00e9 a mais r\u00e1pida do reino, mas por vezes os trav\u00f5es falham.",
    "S3S1_3": "A carruagem da Rainha Mihaela \u00e9 a mais bonita mas n\u00e3o \u00e9 muito conveniente. \u00c9 ligeiramente pesada e um pesadelo para limpar - a lama fica agarrada a todos os elementos decorativos das paredes exteriores.",
    "S3S1_4": "A carruagem do Rei Pablo \u00e9 a mais forte de todo o reino. J\u00e1 sobreviveu a p\u00e9ssimas estradas e at\u00e9 a v\u00e1rios ataques; \u00e9 um \u00eaxito a manter o Rei e a Rainha em seguran\u00e7a.",
    "S3S1_5": "A carruagem da rainha Ana \u00e9 a mais confort\u00e1vel. At\u00e9 o assento do cocheiro \u00e9 feito de materiais muito suaves e confort\u00e1veis. Viajar nesta carruagem \u00e9 um prazer.",
    "S3S1_6": "A carruagem do Rei Tharrenos \u00e9 a maior. Oferece muito espa\u00e7o. Viajar nesta carruagem \u00e9 como estar na nossa sala de estar.",
    "S3S3_1": "Espero que esta visita a carruagens de outros reis e rainhas te tenha inspirado. Agora vamos continuar com o teu projeto!",
    "S4S1_1": "Com a informa\u00e7\u00e3o que reuniste de todas as pessoas com quem falaste, da explora\u00e7\u00e3o de outras carruagens e com a tua opini\u00e3o e intui\u00e7\u00e3o, chegou o momento de avan\u00e7ar para a prototipagem da carruagem.",
    "S4S2_1": "A tua carruagem est\u00e1 muito pobre. Est\u00e1s a construir a carruagem da fam\u00edlia real! E n\u00e3o o carrinho de um comerciante!",
    "S4S2_2": "A tua carruagem \u00e9 t\u00e3o simples que s\u00f3 demorar\u00e1s 2 semanas a construi-la. Podes investir mais tempo, pois tens 6 meses para a entregar. Vamos melhorar a carruagem!",
    "S4S2_3": "A carruagem \u00e9 demasiado pesada e lenta. As viagens v\u00e3o demorar uma eternidade!",
    "S4S2_4": "A carruagem \u00e9 demasiado grosseiropara uma carruagem real,mais parece uma carruagem de camponeses.",
    "S4S2_5": "Tens fazer uma carruagem e n\u00e3o uma charrete. Faz com que seja mais adequada!",
    "S4S2_6": "Da forma como est\u00e1 constru\u00edda, esta carruagem \u00e9 muito fr\u00e1gil. Vai desmontar-se assim que embater numa pedra da cal\u00e7ada.",
    "S4S2_7": "Vais arruinar o reino! Reconsidera as op\u00e7\u00f5es que fizeste para a carruagem e escolhe elementos mais baratos.",
    "S4S2_8": "A fam\u00edlia real precisa da carruagem pronta em 6 meses. Escolhe alguns elementos mais simples para reduzir o tempo de constru\u00e7\u00e3o.",
    "S4S3_1": "Precisas de melhorar o teu projetoantes de continuar.",
    "S4S3_2": "Ok! Vamos testar a carruagem!",
    "S5S0_1": "Agora que o prot\u00f3tipo da carruagem est\u00e1 pronto, vamos apresentar a algumas pessoas e receber o seu feedback antes de apresentar a carruagem ao Rei.",
    "S5S1_1": "Bem, parece-me bastante forte. Devemos experiment\u00e1-la antes de a entregar ao Rei e \u00e0 Rainha.",
    "S5S1_2": "Muito bem! \u00c9 uma boa carruagem. Mas achas que passa por ruas estreitas? Talvez seja melhor test\u00e1-la antes de a entregar.",
    "S5S1_3": "Nada mal. Nada mal, mesmo! Mas achas que \u00e9 elegante o suficiente para a fam\u00edlia real ir a uma cerim\u00f3mia? Devias perguntar \u00e0s pessoas o que acham da carruagem antes de a entregar ao Rei e \u00e0 Rainha.",
    "S5S1_4": "Desculpa, mas n\u00e3o tenho tempo para conversar.",
    "S5S1_5": "Tenho muito para fazer... Pergunta a outra pessoa.",
    "S5S1_6": "Desculpa?",
    "S5S1_7": "Com base no feedback que recebeste, queres rever o teu projeto ou vais ignorar as sugest\u00f5es e manter a carruagem como est\u00e1 agora?",
    "S5S2_1": "Tens tudo pronto para testar a carruagem l\u00e1 fora! Vamos ver se a tua carruagem funciona? Agora, vais sair com a tua carruagem mas ter\u00e1s de parar num cruzamento com tr\u00eas caminhos. Escolhe um dos tr\u00eas caminhos para continuares.",
    "S5S2_2A": "Acabas de chegar \u00e0 cidade com a carruagem mas ningu\u00e9m te viu... Isto n\u00e3o \u00e9 um bom sinal. A carruagem real tem de ser reconhecida por todos! Os habitantes devem querer aproximar-se! Tens de conseguir torn\u00e1-la mais not\u00e1vel...",
    "S5S2_2": "Escolheste acompanhar a tua carruagem com artistas, bandeiras e animais majestosos, para ir ao Conselho de reis e rainhas! Esta op\u00e7\u00e3o n\u00e3o altera o projeto inicial da tua carruagem e permite responder \u00e0 necessidade tempor\u00e1ria de chamar a aten\u00e7\u00e3o para o Rei e a Rainha. Muito bem!",
    "S5S2_3A": "Acabas de chegar \u00e0 cidade de um velho amigo - o Senhor Christophe. Que coincid\u00eancia! Ambos planeiam viajar para Portalona no dia seguinte. Tens de conseguir partilhar a carruagem...",
    "S5S2_3": "Escolheste redesenhar a tua carruagem para a partilhar! Parab\u00e9ns! A maioria das carruagens est\u00e3o inutilizadas 80% do tempo, mas agora pode ser partilhada. Considera tamb\u00e9m a necessidade em partilhar o tempo em que a carruagem pode ser utilizada.",
    "S5S2_4A": "Acabas de passar a ponte de Oslina... Emboscada! Um grupo de ladr\u00f5es! Ufa... Conseguiste escapar! Tens de conseguir proteger a carruagem...",
    "S5S2_4": "Escolheste acompanhar a carruagem com soldados e armas para defender a fam\u00edlia Real! Assim, n\u00e3o precisas de alterar o projeto inicial da carruagem e respondes a uma necessidade excecional de refor\u00e7ar a defesa sem grandes custos. Muito bem!",
    "S5S2B": "Tens mais op\u00e7\u00f5es na tua oficina. Descobre quais!",
    "S5S2C": "Agora que alteraste a carruagem, realiza um novo teste!",
    "S6S1_1": "Chegou o dia que tanto esper\u00e1vamos! Este \u00e9 o momento para apresnetar a carruagem ao Rei e \u00e0 Rainha.",
    "S6S1_2": "Muito bem! Fizeste um trabalho fant\u00e1stico. Estou muito satisfeita com a carruagem.",
    "S6S1_3": "Sim! A carruagem \u00e9 perfeita!",
    "S6S2_1": "Muito obrigado, mas podes pint\u00e1-la com cor de rosa?",
    "S6S2_2": "Adorei, mas podes pint\u00e1-la como um arco-\u00edris?",
    "S6S2_3": "\u00c9 uma carruagem espetacular, mas podes colocar-lhe asas?",
    "S6S2_4": "Gosto muito, mas \u00e9 poss\u00edvel cobri-la com penas?",
    "S6S3_1": "Fizeste um trabalho incr\u00edvel! Isto \u00e9 uma obra de arte! Podes sentir muito orgulho pelo teu trabalho. Todo o reino te agradece! N\u00e3o sei quais s\u00e3o os teus planos para o futuro, mas tens de aproveitar a tua criatividade!",
    "B1": "Criativo",
    "B2": "Pensador cr\u00edtico",
    "B3": "Ouvinte",
    "B4": "Persistente",
    "B5": "Solucionador de problemas",
    "M1": "Agora podes avan\u00e7ar para o pr\u00f3ximo passo",
    "M2": "Clica no personagem para receberes feedback",
    "M3": "Clica no personagem",
    "next.page": "Pr\u00f3xima p\u00e1gina",
    "previous.page": "P\u00e1gina anterior",
    "see.result": "Ver o resultado",
    "next.step": "Pr\u00f3ximo passo",
    "start": "Iniciar",
    "B6": "Fechar",
    "B7": "Dica",
    "B8": "Ir para o workshop",
    "B9": "Diz-nos o teu nome",
    "B10": "Iniciar um novo jogo",
    "B11": "Carregar o jogo anterior",
    "S4L1": "Rodas",
    "S4L2": "Chassis",
    "S4L3": "Assento do condutor",
    "S4L4": "Assentos interiores",
    "S4L5": "Carroceria",
    "S4L6": "Bagageira",
    "N1L1": "Constr\u00f3i a melhor, a mais pr\u00e1tica, a mais vistosa carruagem para a fam\u00edlia real",
    "N1L2": "Personagens",
    "N1L3": "Indicadores",
    "N1L4": "Carruagens",
    "N1L5": "Exemplos",
    "N1L6": "A tua carruagem",
    "N1L7": "Rupturas",
    "N1L8": "Medalhas",
    "N1L9": "A miss\u00e3o",
    "S6A1": "Agrade\u00e7o-vos! Gostei muito deste trabalho! Tive mais ideias enquanto desenhava a melhor carruagem e talvez ainda as possa incluir na vossa carruagem?",
    "S6A2": "Sim, claro!",
    "S6A3": "Bem, talvez pudesse tornar a carruagem mais...",
    "S6A4": "bonita e rodeada de animadores (m\u00fasicos, artistas), bandeiras e animais (elefantes, girafas, camelos, avestruzes) para viajarem at\u00e9 ao conselho dos reis e rainhas! Aposto que todos ficariam impressionados!",
    "S6A5": "amiga do ambiente, podendo ser partilhada! Muitas carruagens ficam inutilizadas 80% do tempo. Compartilhem!",
    "S6A6": "Tens alguma sugest\u00e3o?",
    "S6A7": "Sim! Talvez seja melhor protegerem a carruagem para prepar\u00e1-la para ataques. Uma carroceria robusta n\u00e3o \u00e9 suficiente. Precisam de rodear a carruagem com soldados e escudos presos \u00e0 carroceria. Aposto que impressionam poss\u00edveis atacantes!",
    "ending": "Fim.",
}